//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.239
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScreenshotAnalyzer.Resources.Localisation {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcesGui {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesGui() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScreenshotAnalyzer.Resources.Localisation.ResourcesGui", typeof(ResourcesGui).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A_bbrechen ähnelt.
        /// </summary>
        public static string btnCancel_Caption {
            get {
                return ResourceManager.GetString("btnCancel_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beenden ähnelt.
        /// </summary>
        public static string BtnExit {
            get {
                return ResourceManager.GetString("BtnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _OK ähnelt.
        /// </summary>
        public static string btnOk_Caption {
            get {
                return ResourceManager.GetString("btnOk_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aktuelles Bild &quot;{0}&quot;
        ///Erkannter Text {1}/{2} ähnelt.
        /// </summary>
        public static string CorrectionAssistantModel_InfoString {
            get {
                return ResourceManager.GetString("CorrectionAssistantModel_InfoString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weiter ähnelt.
        /// </summary>
        public static string CorrectionAssistantModel_NextButtonText_Next {
            get {
                return ResourceManager.GetString("CorrectionAssistantModel_NextButtonText_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fertig ähnelt.
        /// </summary>
        public static string CorrectionAssistantModel_NextButtonText_Ready {
            get {
                return ResourceManager.GetString("CorrectionAssistantModel_NextButtonText_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spaltennamen editieren ähnelt.
        /// </summary>
        public static string CtlColumnHeader_btnEditHeader_Text {
            get {
                return ResourceManager.GetString("CtlColumnHeader_btnEditHeader_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neu ähnelt.
        /// </summary>
        public static string CtlListView_btnAddItem_New {
            get {
                return ResourceManager.GetString("CtlListView_btnAddItem_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Löschen ähnelt.
        /// </summary>
        public static string CtlListView_btnDeleteItem_Delete {
            get {
                return ResourceManager.GetString("CtlListView_btnDeleteItem_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Detailangaben ähnelt.
        /// </summary>
        public static string CtlListView_Details {
            get {
                return ResourceManager.GetString("CtlListView_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ausgabe Access Datenbank ähnelt.
        /// </summary>
        public static string CtlProfileDetails_AccessOutputPath {
            get {
                return ResourceManager.GetString("CtlProfileDetails_AccessOutputPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beschreibung (optional) ähnelt.
        /// </summary>
        public static string CtlProfileDetails_Description {
            get {
                return ResourceManager.GetString("CtlProfileDetails_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string CtlProfileDetails_Name {
            get {
                return ResourceManager.GetString("CtlProfileDetails_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pfad zu den Einstellungen ähnelt.
        /// </summary>
        public static string CtlProfileDetails_PathToDatabaseFile {
            get {
                return ResourceManager.GetString("CtlProfileDetails_PathToDatabaseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Liste leeren ähnelt.
        /// </summary>
        public static string CtlScreenshotList_btnClearImages_ClearList {
            get {
                return ResourceManager.GetString("CtlScreenshotList_btnClearImages_ClearList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ausgewähltes Bild löschen ähnelt.
        /// </summary>
        public static string CtlScreenshotList_btnDeleteImage_DeleteSelectedImage {
            get {
                return ResourceManager.GetString("CtlScreenshotList_btnDeleteImage_DeleteSelectedImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bilder hinzufügen ähnelt.
        /// </summary>
        public static string CtlScreenshotList_btnLoadImages_AddImages {
            get {
                return ResourceManager.GetString("CtlScreenshotList_btnLoadImages_AddImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Geladene Bilder ähnelt.
        /// </summary>
        public static string CtlScreenshotList_LoadedImages {
            get {
                return ResourceManager.GetString("CtlScreenshotList_LoadedImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anker Rechteck ähnelt.
        /// </summary>
        public static string CtlSelectOcrAreas_AnchorRect {
            get {
                return ResourceManager.GetString("CtlSelectOcrAreas_AnchorRect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bearbeitungsmodi ähnelt.
        /// </summary>
        public static string CtlSelectOcrAreas_EditModes {
            get {
                return ResourceManager.GetString("CtlSelectOcrAreas_EditModes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 1. Ankerpunkt selektieren ähnelt.
        /// </summary>
        public static string CtlSelectOcrAreas_rbSelectAnchor_Text {
            get {
                return ResourceManager.GetString("CtlSelectOcrAreas_rbSelectAnchor_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 2. Text selektieren ähnelt.
        /// </summary>
        public static string CtlSelectOcrAreas_rbSelectOcrArea_Text {
            get {
                return ResourceManager.GetString("CtlSelectOcrAreas_rbSelectOcrArea_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 3. Rechtecke bearbeiten ähnelt.
        /// </summary>
        public static string CtlSelectOcrAreas_rbSelectRectangle_Text {
            get {
                return ResourceManager.GetString("CtlSelectOcrAreas_rbSelectRectangle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Selektiertes Rechteck ähnelt.
        /// </summary>
        public static string CtlSelectOcrAreas_SelectedRect {
            get {
                return ResourceManager.GetString("CtlSelectOcrAreas_SelectedRect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Text Rechteck ähnelt.
        /// </summary>
        public static string CtlSelectOcrAreas_TextRect {
            get {
                return ResourceManager.GetString("CtlSelectOcrAreas_TextRect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beschreibung ähnelt.
        /// </summary>
        public static string CtlTableDetails_Description {
            get {
                return ResourceManager.GetString("CtlTableDetails_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string CtlTableDetails_Name {
            get {
                return ResourceManager.GetString("CtlTableDetails_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tabellen Name ähnelt.
        /// </summary>
        public static string CtlTableDetails_TableName {
            get {
                return ResourceManager.GetString("CtlTableDetails_TableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Übersicht über die Erkennungsergebnisse ähnelt.
        /// </summary>
        public static string CtlTextRecognitionResult_OverviewInfoString {
            get {
                return ResourceManager.GetString("CtlTextRecognitionResult_OverviewInfoString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wörter korrigieren ähnelt.
        /// </summary>
        public static string DlgCorrectionAssistant_CorrectWords {
            get {
                return ResourceManager.GetString("DlgCorrectionAssistant_CorrectWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erkennungsübersicht ähnelt.
        /// </summary>
        public static string DlgCorrectionAssistant_RecognitionOverview {
            get {
                return ResourceManager.GetString("DlgCorrectionAssistant_RecognitionOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Text Korrektur ähnelt.
        /// </summary>
        public static string DlgCorrectionAssistant_Title {
            get {
                return ResourceManager.GetString("DlgCorrectionAssistant_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schließen ähnelt.
        /// </summary>
        public static string DlgInfo_btnClose_Close {
            get {
                return ResourceManager.GetString("DlgInfo_btnClose_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fax:  ähnelt.
        /// </summary>
        public static string DlgInfo_Fax {
            get {
                return ResourceManager.GetString("DlgInfo_Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Telefon:  ähnelt.
        /// </summary>
        public static string DlgInfo_Phone {
            get {
                return ResourceManager.GetString("DlgInfo_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Support: ähnelt.
        /// </summary>
        public static string DlgInfo_Support {
            get {
                return ResourceManager.GetString("DlgInfo_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Text extrahieren ähnelt.
        /// </summary>
        public static string DlgMainWindow_btnExtractText_Caption {
            get {
                return ResourceManager.GetString("DlgMainWindow_btnExtractText_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Text extrahieren für alle ähnelt.
        /// </summary>
        public static string DlgMainWindow_btnExtractTextForAll_Caption {
            get {
                return ResourceManager.GetString("DlgMainWindow_btnExtractTextForAll_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Info ähnelt.
        /// </summary>
        public static string DlgMainWindow_btnInfo_Caption {
            get {
                return ResourceManager.GetString("DlgMainWindow_btnInfo_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datenbank upgraden ähnelt.
        /// </summary>
        public static string DlgMainWindow_btnUpdateDatabase_UpgradeDatabase {
            get {
                return ResourceManager.GetString("DlgMainWindow_btnUpdateDatabase_UpgradeDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Access Datenbank exportieren ähnelt.
        /// </summary>
        public static string DlgMainWindow_btnUseExportAccess_Caption {
            get {
                return ResourceManager.GetString("DlgMainWindow_btnUseExportAccess_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rechtecke übertragen ähnelt.
        /// </summary>
        public static string DlgMainWindow_btnUseSelectionForAll_Caption {
            get {
                return ResourceManager.GetString("DlgMainWindow_btnUseSelectionForAll_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Profil ähnelt.
        /// </summary>
        public static string DlgMainWindow_Profile {
            get {
                return ResourceManager.GetString("DlgMainWindow_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Screenshot Gruppe ähnelt.
        /// </summary>
        public static string DlgMainWindow_ScreenshotGroup {
            get {
                return ResourceManager.GetString("DlgMainWindow_ScreenshotGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte auswaehlen... ähnelt.
        /// </summary>
        public static string DlgMainWindow_Select {
            get {
                return ResourceManager.GetString("DlgMainWindow_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neues Profil erstellen ähnelt.
        /// </summary>
        public static string DlgNewProfile_Caption {
            get {
                return ResourceManager.GetString("DlgNewProfile_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abbrechen ähnelt.
        /// </summary>
        public static string DlgPopupProgress_btnAbort_Caption {
            get {
                return ResourceManager.GetString("DlgPopupProgress_btnAbort_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Extrahierte Texte ähnelt.
        /// </summary>
        public static string DlgTextTable_Caption {
            get {
                return ResourceManager.GetString("DlgTextTable_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler:  ähnelt.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Möchten Sie das Profil {0} wirklich löschen? ähnelt.
        /// </summary>
        public static string ListViewProfileModel_DeleteItem_DeleteProfileQuestion {
            get {
                return ResourceManager.GetString("ListViewProfileModel_DeleteItem_DeleteProfileQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Löschen des Profils:  ähnelt.
        /// </summary>
        public static string ListViewProfileModel_DeleteItem_Error_DeletingProfile {
            get {
                return ResourceManager.GetString("ListViewProfileModel_DeleteItem_Error_DeletingProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte zuerst ein Profil anlegen und auswählen ähnelt.
        /// </summary>
        public static string ListViewTableModel_AddItem_ErrorSelectProfileFirst {
            get {
                return ResourceManager.GetString("ListViewTableModel_AddItem_ErrorSelectProfileFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Möchten Sie die Gruppe {0} wirklich löschen? ähnelt.
        /// </summary>
        public static string ListViewTableModel_DeleteItem_ConfirmationMessage {
            get {
                return ResourceManager.GetString("ListViewTableModel_DeleteItem_ConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte zuerst im Profil einen Pfad zur Datenbank auswählen. ähnelt.
        /// </summary>
        public static string MainWindowModel_ExportAccessDatabase_Error_NoAccessOutputPathSelected {
            get {
                return ResourceManager.GetString("MainWindowModel_ExportAccessDatabase_Error_NoAccessOutputPathSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kein zu exportierendes Ergebnis vorhanden, bitte zuerst die Texterkennung durchführen. ähnelt.
        /// </summary>
        public static string MainWindowModel_ExportAccessDatabase_Error_NoRecognitionResultPresent {
            get {
                return ResourceManager.GetString("MainWindowModel_ExportAccessDatabase_Error_NoRecognitionResultPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keine Screenshot Gruppe ausgewählt. ähnelt.
        /// </summary>
        public static string MainWindowModel_ExportAccessDatabase_Error_NoScreenshotGroupSelected {
            get {
                return ResourceManager.GetString("MainWindowModel_ExportAccessDatabase_Error_NoScreenshotGroupSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte zuerst einen Tabellennamen in der Screenshot Gruppe einstellen. ähnelt.
        /// </summary>
        public static string MainWindowModel_ExportAccessDatabase_Error_NoTablenameSelected {
            get {
                return ResourceManager.GetString("MainWindowModel_ExportAccessDatabase_Error_NoTablenameSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verwaltung ähnelt.
        /// </summary>
        public static string MainWindowModel_Navigation_Management {
            get {
                return ResourceManager.GetString("MainWindowModel_Navigation_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Profile ähnelt.
        /// </summary>
        public static string MainWindowModel_Navigation_Profile {
            get {
                return ResourceManager.GetString("MainWindowModel_Navigation_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erkennungs Ergebnis ähnelt.
        /// </summary>
        public static string MainWindowModel_Navigation_RecognitionResult {
            get {
                return ResourceManager.GetString("MainWindowModel_Navigation_RecognitionResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Screenshot Gruppen ähnelt.
        /// </summary>
        public static string MainWindowModel_Navigation_ScreenshotGroups {
            get {
                return ResourceManager.GetString("MainWindowModel_Navigation_ScreenshotGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Textauswahl ähnelt.
        /// </summary>
        public static string MainWindowModel_Navigation_Textselection {
            get {
                return ResourceManager.GetString("MainWindowModel_Navigation_Textselection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Laden des Profils &quot;{0}&quot;: {1} ähnelt.
        /// </summary>
        public static string MainWindowModel_SelectedProfile_Error_LoadingProfile {
            get {
                return ResourceManager.GetString("MainWindowModel_SelectedProfile_Error_LoadingProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keine Screenshotgruppe ausgewählt ähnelt.
        /// </summary>
        public static string SelectOcrAreasModel_ExtractText_ErrorNoScreenshotgroupSelected {
            get {
                return ResourceManager.GetString("SelectOcrAreasModel_ExtractText_ErrorNoScreenshotgroupSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kein Screenshot ausgewählt ähnelt.
        /// </summary>
        public static string SelectOcrAreasModel_ExtractText_NoScreenshotSelected {
            get {
                return ResourceManager.GetString("SelectOcrAreasModel_ExtractText_NoScreenshotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler:  ähnelt.
        /// </summary>
        public static string SelectOcrAreasModel_progress_DoWork_Error {
            get {
                return ResourceManager.GetString("SelectOcrAreasModel_progress_DoWork_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte geben Sie den Namen des Profils ein ähnelt.
        /// </summary>
        public static string TxtEnterProfileName {
            get {
                return ResourceManager.GetString("TxtEnterProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte geben Sie den Pfad an indem das Profil gespeichert werden soll, bzw. aus dem das Profil importiert werden soll. ähnelt.
        /// </summary>
        public static string TxtEnterProfilePath {
            get {
                return ResourceManager.GetString("TxtEnterProfilePath", resourceCulture);
            }
        }
    }
}
