//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.225
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBalanceKitConfig.Localisation {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eBalanceKitConfig.Localisation.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The company could not be deleted, since it is currently used from one or more reports. ähnelt.
        /// </summary>
        internal static string CompanyInUse {
            get {
                return ResourceManager.GetString("CompanyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not add company:  ähnelt.
        /// </summary>
        internal static string CompanyManagerAdd {
            get {
                return ResourceManager.GetString("CompanyManagerAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not delete company:  ähnelt.
        /// </summary>
        internal static string CompanyManagerDelete {
            get {
                return ResourceManager.GetString("CompanyManagerDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not update company:  ähnelt.
        /// </summary>
        internal static string CompanyManagerUpdate {
            get {
                return ResourceManager.GetString("CompanyManagerUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not find the application config file ähnelt.
        /// </summary>
        internal static string ConfigFileNotFound {
            get {
                return ResourceManager.GetString("ConfigFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to create the application config file ähnelt.
        /// </summary>
        internal static string CreateAppConfigFailed {
            get {
                return ResourceManager.GetString("CreateAppConfigFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not create config directory &quot;{0}&quot; ähnelt.
        /// </summary>
        internal static string CreateConfigDirFailed {
            get {
                return ResourceManager.GetString("CreateConfigDirFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to create table {0} ähnelt.
        /// </summary>
        internal static string CreateTableFailed {
            get {
                return ResourceManager.GetString("CreateTableFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error during database initialisation ähnelt.
        /// </summary>
        internal static string DbInitFailed {
            get {
                return ResourceManager.GetString("DbInitFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to upgrade the database to version {0} ähnelt.
        /// </summary>
        internal static string DbUpgradeFailed {
            get {
                return ResourceManager.GetString("DbUpgradeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Updating database to Version {0} ähnelt.
        /// </summary>
        internal static string DbUpgradeProgress {
            get {
                return ResourceManager.GetString("DbUpgradeProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not add document:  ähnelt.
        /// </summary>
        internal static string DocumentManagerAdd {
            get {
                return ResourceManager.GetString("DocumentManagerAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not delete document:  ähnelt.
        /// </summary>
        internal static string DocumentManagerDelete {
            get {
                return ResourceManager.GetString("DocumentManagerDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not update document:  ähnelt.
        /// </summary>
        internal static string DocumentManagerUpdate {
            get {
                return ResourceManager.GetString("DocumentManagerUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not add period:  ähnelt.
        /// </summary>
        internal static string DocumentPeriodManagerAdd {
            get {
                return ResourceManager.GetString("DocumentPeriodManagerAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not period:  ähnelt.
        /// </summary>
        internal static string DocumentPeriodManagerDelete {
            get {
                return ResourceManager.GetString("DocumentPeriodManagerDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not period:  ähnelt.
        /// </summary>
        internal static string DocumentPeriodManagerUpdate {
            get {
                return ResourceManager.GetString("DocumentPeriodManagerUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to add dataset:  ähnelt.
        /// </summary>
        internal static string FailedToAddDataset {
            get {
                return ResourceManager.GetString("FailedToAddDataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to copy data for table {0} from backup table ähnelt.
        /// </summary>
        internal static string FailedToCopyData {
            get {
                return ResourceManager.GetString("FailedToCopyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to remove backup tables ähnelt.
        /// </summary>
        internal static string FailedToDeleteBackupTables {
            get {
                return ResourceManager.GetString("FailedToDeleteBackupTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to delete dataset:  ähnelt.
        /// </summary>
        internal static string FailedToDeleteDataset {
            get {
                return ResourceManager.GetString("FailedToDeleteDataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to remove table {0} ähnelt.
        /// </summary>
        internal static string FailedToDeleteTable {
            get {
                return ResourceManager.GetString("FailedToDeleteTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not load data for value transfer of commercial to tax values:  ähnelt.
        /// </summary>
        internal static string FailedToLoadTransferHBST {
            get {
                return ResourceManager.GetString("FailedToLoadTransferHBST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to rename tables ähnelt.
        /// </summary>
        internal static string FailedToRenameTables {
            get {
                return ResourceManager.GetString("FailedToRenameTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to update dataset:  ähnelt.
        /// </summary>
        internal static string FailedToUpdateDataset {
            get {
                return ResourceManager.GetString("FailedToUpdateDataset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to update table {0} ähnelt.
        /// </summary>
        internal static string FailedToUpdateTable {
            get {
                return ResourceManager.GetString("FailedToUpdateTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The datast could not be deleted, since it is currently assigned to at least one income statements or balance sheet position. ähnelt.
        /// </summary>
        internal static string HeaderInUse {
            get {
                return ResourceManager.GetString("HeaderInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid user or password. ähnelt.
        /// </summary>
        internal static string InvalidUserOrPassword {
            get {
                return ResourceManager.GetString("InvalidUserOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The eBalance-Kit database has been updated to a newer version, please install the eBalance-Kit in version {0} or higher. ähnelt.
        /// </summary>
        internal static string ProgramOutOfDate {
            get {
                return ResourceManager.GetString("ProgramOutOfDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Creating new account assignments... ähnelt.
        /// </summary>
        internal static string ProgressAddAssignments {
            get {
                return ResourceManager.GetString("ProgressAddAssignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deleting account assignments... ähnelt.
        /// </summary>
        internal static string ProgressDeleteAssignments {
            get {
                return ResourceManager.GetString("ProgressDeleteAssignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to read the application config file ähnelt.
        /// </summary>
        internal static string ReadAppConfigFailed {
            get {
                return ResourceManager.GetString("ReadAppConfigFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The system could not be deleted, since it is currently used from one or more reports. ähnelt.
        /// </summary>
        internal static string SystemInUse {
            get {
                return ResourceManager.GetString("SystemInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not add system:  ähnelt.
        /// </summary>
        internal static string SystemManagerAdd {
            get {
                return ResourceManager.GetString("SystemManagerAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not delete system:  ähnelt.
        /// </summary>
        internal static string SystemManagerDelete {
            get {
                return ResourceManager.GetString("SystemManagerDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not update system:  ähnelt.
        /// </summary>
        internal static string SystemManagerUpdate {
            get {
                return ResourceManager.GetString("SystemManagerUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while loading the taxonomy could not be loaded:  ähnelt.
        /// </summary>
        internal static string TaxonomiesLoadError {
            get {
                return ResourceManager.GetString("TaxonomiesLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not add template:  ähnelt.
        /// </summary>
        internal static string TemplateManagerAdd {
            get {
                return ResourceManager.GetString("TemplateManagerAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not delete template:  ähnelt.
        /// </summary>
        internal static string TemplateManagerDelete {
            get {
                return ResourceManager.GetString("TemplateManagerDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not update template:  ähnelt.
        /// </summary>
        internal static string TemplateManagerUpdate {
            get {
                return ResourceManager.GetString("TemplateManagerUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to rename column {0} in table {1} ähnelt.
        /// </summary>
        internal static string UpgradeRenameColumnFailed {
            get {
                return ResourceManager.GetString("UpgradeRenameColumnFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not add user:  ähnelt.
        /// </summary>
        internal static string UserManagerAdd {
            get {
                return ResourceManager.GetString("UserManagerAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not delete user:  ähnelt.
        /// </summary>
        internal static string UserManagerDelete {
            get {
                return ResourceManager.GetString("UserManagerDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not update user:  ähnelt.
        /// </summary>
        internal static string UserManagerUpdate {
            get {
                return ResourceManager.GetString("UserManagerUpdate", resourceCulture);
            }
        }
    }
}
