//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.269
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBalanceKitResources.Localisation {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcesAuditCorrections {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesAuditCorrections() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eBalanceKitResources.Localisation.ResourcesAuditCorrections", typeof(ResourcesAuditCorrections).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die add correction value ähnelt.
        /// </summary>
        public static string AddKorrektionValue {
            get {
                return ResourceManager.GetString("AddKorrektionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The correction belongs to the currently selected correction dataset ähnelt.
        /// </summary>
        public static string AssignedCorrectionIsSelectedIconTooltip {
            get {
                return ResourceManager.GetString("AssignedCorrectionIsSelectedIconTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die tax audits ähnelt.
        /// </summary>
        public static string AuditMode {
            get {
                return ResourceManager.GetString("AuditMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In audit mode you are able to enter corrections from tax audits for reports which are already sent. In detail you have the following options to do that:
        ///
        ///1. Enter correction values for any position:
        ///TODO
        ///
        ///2. Enter correction values for reconciliations:
        ///TODO ähnelt.
        /// </summary>
        public static string AuditModeDescription {
            get {
                return ResourceManager.GetString("AuditModeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Audit Mode ähnelt.
        /// </summary>
        public static string AuditModeDialogCaption {
            get {
                return ResourceManager.GetString("AuditModeDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Audit Mode ähnelt.
        /// </summary>
        public static string AuditModeTooltip {
            get {
                return ResourceManager.GetString("AuditModeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die transfer of audit corrections - problems ähnelt.
        /// </summary>
        public static string CheckProblemPdfHead {
            get {
                return ResourceManager.GetString("CheckProblemPdfHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Correction Datasets ähnelt.
        /// </summary>
        public static string CorrectionDatasets {
            get {
                return ResourceManager.GetString("CorrectionDatasets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A correction dataset can contain any number of value corrections from tax audits and is used to outline transactions with regard to content.
        ///
        ///A comment could be denoted for every dataset to document the backgrounds of the correction. ähnelt.
        /// </summary>
        public static string CorrectionDatasetsInfo {
            get {
                return ResourceManager.GetString("CorrectionDatasetsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die correction dataset ähnelt.
        /// </summary>
        public static string DefaultName {
            get {
                return ResourceManager.GetString("DefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Really delete correction &quot;{0}&quot;? 
        ///
        ///This action unrecoverable deletes the selected correction together with all included correction transactions! ähnelt.
        /// </summary>
        public static string DeleteCorrection {
            get {
                return ResourceManager.GetString("DeleteCorrection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete correction? ähnelt.
        /// </summary>
        public static string DeleteCorrectionCaption {
            get {
                return ResourceManager.GetString("DeleteCorrectionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Really delete correction transaction for Position &quot;{0}&quot;? ähnelt.
        /// </summary>
        public static string DeleteCorrectionTransaction {
            get {
                return ResourceManager.GetString("DeleteCorrectionTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete correction transaction? ähnelt.
        /// </summary>
        public static string DeleteCorrectionTransactionCaption {
            get {
                return ResourceManager.GetString("DeleteCorrectionTransactionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die element &quot;{0}&quot; is disabled or computed ähnelt.
        /// </summary>
        public static string ElementIsDisabledOrComputed {
            get {
                return ResourceManager.GetString("ElementIsDisabledOrComputed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die no representation in the GaapPresentationTrees found for element &quot;{0}&quot; ähnelt.
        /// </summary>
        public static string ProblemEntryNoGaapPresentationTree {
            get {
                return ResourceManager.GetString("ProblemEntryNoGaapPresentationTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die checking correction &quot;{0}&quot;  ähnelt.
        /// </summary>
        public static string ProgressCorrectionChecking {
            get {
                return ResourceManager.GetString("ProgressCorrectionChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die checking correction(s) for report &quot;{0}&quot; ähnelt.
        /// </summary>
        public static string ProgressDocumentChecking {
            get {
                return ResourceManager.GetString("ProgressDocumentChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die applying correction(s) for report &quot;{0}&quot; ähnelt.
        /// </summary>
        public static string ProgressDocumentExecuting {
            get {
                return ResourceManager.GetString("ProgressDocumentExecuting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die loading report &quot;{0}&quot; ähnelt.
        /// </summary>
        public static string ProgressDocumentLoading {
            get {
                return ResourceManager.GetString("ProgressDocumentLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No report selected ähnelt.
        /// </summary>
        public static string TransferMessageNoReportSelected {
            get {
                return ResourceManager.GetString("TransferMessageNoReportSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die no transacion selected ähnelt.
        /// </summary>
        public static string TransferMessageNoTransactionSelected {
            get {
                return ResourceManager.GetString("TransferMessageNoTransactionSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Applied selected corrections successful to the selected reports. ähnelt.
        /// </summary>
        public static string TransferSuccessMessage {
            get {
                return ResourceManager.GetString("TransferSuccessMessage", resourceCulture);
            }
        }
    }
}
