//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.544
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBalanceKitResources.Localisation {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcesReconciliation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesReconciliation() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eBalanceKitResources.Localisation.ResourcesReconciliation", typeof(ResourcesReconciliation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add new reconciliation ähnelt.
        /// </summary>
        public static string AddReconciliationDlgCaption {
            get {
                return ResourceManager.GetString("AddReconciliationDlgCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Amount ähnelt.
        /// </summary>
        public static string AmountCaption {
            get {
                return ResourceManager.GetString("AmountCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure to delete the selected reconciliation? ähnelt.
        /// </summary>
        public static string AreYouSureDeleteReconciliation {
            get {
                return ResourceManager.GetString("AreYouSureDeleteReconciliation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die set position as destination for selected reclassification ähnelt.
        /// </summary>
        public static string AssignDestinationPositionTooltip {
            get {
                return ResourceManager.GetString("AssignDestinationPositionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die reconciliation is assigned to the currently selected reconciliation dataset ähnelt.
        /// </summary>
        public static string AssignedReconciliationIsSelectedIconTooltip {
            get {
                return ResourceManager.GetString("AssignedReconciliationIsSelectedIconTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Assignment not possible ähnelt.
        /// </summary>
        public static string AssignmentNotPossibleInformationCaption {
            get {
                return ResourceManager.GetString("AssignmentNotPossibleInformationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die add position to selected reconciliation dataset ähnelt.
        /// </summary>
        public static string AssignPositionTooltip {
            get {
                return ResourceManager.GetString("AssignPositionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die set position as source for selected reclassification ähnelt.
        /// </summary>
        public static string AssignSourcePositionTooltip {
            get {
                return ResourceManager.GetString("AssignSourcePositionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die correction of previous year value: ähnelt.
        /// </summary>
        public static string AuditCorrectionPreviousYearValueCaption {
            get {
                return ResourceManager.GetString("AuditCorrectionPreviousYearValueCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Correction of previous year value ähnelt.
        /// </summary>
        public static string AuditCorrectionsPreviousYear {
            get {
                return ResourceManager.GetString("AuditCorrectionsPreviousYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Assets ähnelt.
        /// </summary>
        public static string BalanceListAssets {
            get {
                return ResourceManager.GetString("BalanceListAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Liabilities ähnelt.
        /// </summary>
        public static string BalanceListLiabilities {
            get {
                return ResourceManager.GetString("BalanceListLiabilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change input mode ähnelt.
        /// </summary>
        public static string ChangeInputMode {
            get {
                return ResourceManager.GetString("ChangeInputMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose transactions to delete ähnelt.
        /// </summary>
        public static string ChooseTransactionsToDeleteCaption {
            get {
                return ResourceManager.GetString("ChooseTransactionsToDeleteCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Comment ähnelt.
        /// </summary>
        public static string CommentCaption {
            get {
                return ResourceManager.GetString("CommentCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Optional comment of the reconciliation fact.  Value will be transfered when sending the report to the financial administration. ähnelt.
        /// </summary>
        public static string CommentInfo {
            get {
                return ResourceManager.GetString("CommentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die commercial balance value ähnelt.
        /// </summary>
        public static string CommercialBalanceValue {
            get {
                return ResourceManager.GetString("CommercialBalanceValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die this position contains a computed reconciliation value ähnelt.
        /// </summary>
        public static string ContainsComputedReconciliationValue {
            get {
                return ResourceManager.GetString("ContainsComputedReconciliationValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die this position contains a manual reconciliation value ähnelt.
        /// </summary>
        public static string ContainsManualReconciliationValue {
            get {
                return ResourceManager.GetString("ContainsManualReconciliationValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete All ähnelt.
        /// </summary>
        public static string DeleteAllPreviousYearValuesCaption {
            get {
                return ResourceManager.GetString("DeleteAllPreviousYearValuesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to delete all imported reconciliations? ähnelt.
        /// </summary>
        public static string DeleteAllReconciliation {
            get {
                return ResourceManager.GetString("DeleteAllReconciliation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not delete reconciliation dataset:  ähnelt.
        /// </summary>
        public static string DeleteException {
            get {
                return ResourceManager.GetString("DeleteException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die delete Position ähnelt.
        /// </summary>
        public static string DeletePosition {
            get {
                return ResourceManager.GetString("DeletePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete Reconciliation ähnelt.
        /// </summary>
        public static string DeleteReconciliation {
            get {
                return ResourceManager.GetString("DeleteReconciliation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete successful ähnelt.
        /// </summary>
        public static string DeleteReconciliationSuccessfulTitle {
            get {
                return ResourceManager.GetString("DeleteReconciliationSuccessfulTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not delete transaction:  ähnelt.
        /// </summary>
        public static string DeleteTransactionException {
            get {
                return ResourceManager.GetString("DeleteTransactionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description ähnelt.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Drag the destination item here from the tree to edit. ähnelt.
        /// </summary>
        public static string DragDestinationItemHereCaption {
            get {
                return ResourceManager.GetString("DragDestinationItemHereCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Drag an item here from the tree to edit. ähnelt.
        /// </summary>
        public static string DragItemsHereCaption {
            get {
                return ResourceManager.GetString("DragItemsHereCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Drag the source item here from the tree to edit. ähnelt.
        /// </summary>
        public static string DragSourceItemHereCaption {
            get {
                return ResourceManager.GetString("DragSourceItemHereCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die empty reconciliation - new positions can be added using drag&amp;drop ähnelt.
        /// </summary>
        public static string EmptyCustomReconciliationNote {
            get {
                return ResourceManager.GetString("EmptyCustomReconciliationNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die empty reconciliation - new positions can only be added using import ähnelt.
        /// </summary>
        public static string EmptyImportedReconciliationNote {
            get {
                return ResourceManager.GetString("EmptyImportedReconciliationNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No dataset found for this reconciliation type. Click on the &quot;New&quot; button to create a new reconciliation dataset. ähnelt.
        /// </summary>
        public static string EmptyListNote {
            get {
                return ResourceManager.GetString("EmptyListNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;no name&gt; ähnelt.
        /// </summary>
        public static string EmptyReconciliationName {
            get {
                return ResourceManager.GetString("EmptyReconciliationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The current report already contains previous year reconciliation values. If you continue, all existing previous year values will be replaced with the imported values. ähnelt.
        /// </summary>
        public static string ExistingPreviousValuesWarning {
            get {
                return ResourceManager.GetString("ExistingPreviousValuesWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Continue import? ähnelt.
        /// </summary>
        public static string ExistingPreviousValuesWarningCaption {
            get {
                return ResourceManager.GetString("ExistingPreviousValuesWarningCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Next ähnelt.
        /// </summary>
        public static string ImportNextButton {
            get {
                return ResourceManager.GetString("ImportNextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import not possible ähnelt.
        /// </summary>
        public static string ImportNotPossible {
            get {
                return ResourceManager.GetString("ImportNotPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Prev. ähnelt.
        /// </summary>
        public static string ImportPreviousButton {
            get {
                return ResourceManager.GetString("ImportPreviousButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import of previous year values ähnelt.
        /// </summary>
        public static string ImportPreviousYearCaption {
            get {
                return ResourceManager.GetString("ImportPreviousYearCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import previous year values available when previous year reports are present ähnelt.
        /// </summary>
        public static string ImportPreviousYearValuesTooltip {
            get {
                return ResourceManager.GetString("ImportPreviousYearValuesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data import was successful ähnelt.
        /// </summary>
        public static string ImportSuccessfulMessage {
            get {
                return ResourceManager.GetString("ImportSuccessfulMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Income Statement ähnelt.
        /// </summary>
        public static string IncomeStatement {
            get {
                return ResourceManager.GetString("IncomeStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid file format ähnelt.
        /// </summary>
        public static string InvalidFormatError {
            get {
                return ResourceManager.GetString("InvalidFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Label ähnelt.
        /// </summary>
        public static string LabelCaption {
            get {
                return ResourceManager.GetString("LabelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not load reconciliation datasets:  ähnelt.
        /// </summary>
        public static string LoadException {
            get {
                return ResourceManager.GetString("LoadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Menu item will be available when corresponding data are present ähnelt.
        /// </summary>
        public static string MenuItemAvailibleWhenDataPresentTooltip {
            get {
                return ResourceManager.GetString("MenuItemAvailibleWhenDataPresentTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Previous year report has no reconciliation transactions therefore import is not possible ähnelt.
        /// </summary>
        public static string MessagePrevYearHasNoTransactions {
            get {
                return ResourceManager.GetString("MessagePrevYearHasNoTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string NameCaption {
            get {
                return ResourceManager.GetString("NameCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Only for internal use. Value will not be transfered when sending the report to the financial administration. ähnelt.
        /// </summary>
        public static string NameInfo {
            get {
                return ResourceManager.GetString("NameInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New reconciliation ähnelt.
        /// </summary>
        public static string NewReconciliation {
            get {
                return ResourceManager.GetString("NewReconciliation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die assistant for new reconliliation. ähnelt.
        /// </summary>
        public static string NewReconciliationAssistant {
            get {
                return ResourceManager.GetString("NewReconciliationAssistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General ähnelt.
        /// </summary>
        public static string NewReconciliationGeneralCaption {
            get {
                return ResourceManager.GetString("NewReconciliationGeneralCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Selection of reconciliation type ähnelt.
        /// </summary>
        public static string NewReconciliationSelectionCaption {
            get {
                return ResourceManager.GetString("NewReconciliationSelectionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There are no existing previous year reports with reconciliation values. ähnelt.
        /// </summary>
        public static string NoExistingReportsWithPreviousYearValues {
            get {
                return ResourceManager.GetString("NoExistingReportsWithPreviousYearValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select a dataset to edit details. ähnelt.
        /// </summary>
        public static string NoItemSelectedNote {
            get {
                return ResourceManager.GetString("NoItemSelectedNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No selected reconciliation ähnelt.
        /// </summary>
        public static string NoSelectedReconciliation {
            get {
                return ResourceManager.GetString("NoSelectedReconciliation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Parameter missing ähnelt.
        /// </summary>
        public static string ParameterMissing {
            get {
                return ResourceManager.GetString("ParameterMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Positions ähnelt.
        /// </summary>
        public static string PositionsCaption {
            get {
                return ResourceManager.GetString("PositionsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reconciliation value previous year ähnelt.
        /// </summary>
        public static string PreviousYearValue {
            get {
                return ResourceManager.GetString("PreviousYearValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die reconciliation value previous year: ähnelt.
        /// </summary>
        public static string PreviousYearValueCaption {
            get {
                return ResourceManager.GetString("PreviousYearValueCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Previous year values can be entered directly in the adjacent tree view. To enter these values you need to enable the Option &quot;Enter previous year values&quot; in the configuration ( ähnelt.
        /// </summary>
        public static string PreviousYearValueInfoPart1 {
            get {
                return ResourceManager.GetString("PreviousYearValueInfoPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ). ähnelt.
        /// </summary>
        public static string PreviousYearValueInfoPart2 {
            get {
                return ResourceManager.GetString("PreviousYearValueInfoPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reconciliation value previous year ähnelt.
        /// </summary>
        public static string PreviousYearValues {
            get {
                return ResourceManager.GetString("PreviousYearValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data are being exported ... ähnelt.
        /// </summary>
        public static string ProgressExportData {
            get {
                return ResourceManager.GetString("ProgressExportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data are being imported ... ähnelt.
        /// </summary>
        public static string ProgressImportData {
            get {
                return ResourceManager.GetString("ProgressImportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reference list is being saved ... ähnelt.
        /// </summary>
        public static string ProgressSaveReferenceList {
            get {
                return ResourceManager.GetString("ProgressSaveReferenceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All reconciliations of current year will be deleted, do you want to proceed? ähnelt.
        /// </summary>
        public static string QuestionDeleteAllCurrentYearReconciliations {
            get {
                return ResourceManager.GetString("QuestionDeleteAllCurrentYearReconciliations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to delete all imported values? ähnelt.
        /// </summary>
        public static string QuestionDeleteAllImportedValues {
            get {
                return ResourceManager.GetString("QuestionDeleteAllImportedValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to delete all previous year values? ähnelt.
        /// </summary>
        public static string QuestionDeleteAllPreviousYearValues {
            get {
                return ResourceManager.GetString("QuestionDeleteAllPreviousYearValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All tax balance value reconciliations will be deleted, do you want to proceed? ähnelt.
        /// </summary>
        public static string QuestionDeleteAllTaxBalanceValueReconciliations {
            get {
                return ResourceManager.GetString("QuestionDeleteAllTaxBalanceValueReconciliations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reconciliation ähnelt.
        /// </summary>
        public static string Reconciliation {
            get {
                return ResourceManager.GetString("Reconciliation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import reconciliation CSV-Files ähnelt.
        /// </summary>
        public static string ReconciliationAssistantImportButtonCaption {
            get {
                return ResourceManager.GetString("ReconciliationAssistantImportButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die What do you want to do? ähnelt.
        /// </summary>
        public static string ReconciliationAssistantText {
            get {
                return ResourceManager.GetString("ReconciliationAssistantText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reconciliation assistant ähnelt.
        /// </summary>
        public static string ReconciliationAssistantTitle {
            get {
                return ResourceManager.GetString("ReconciliationAssistantTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Welcome to the reconciliation import assistant ähnelt.
        /// </summary>
        public static string ReconciliationAssistantWelcome {
            get {
                return ResourceManager.GetString("ReconciliationAssistantWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Audit Corrections ähnelt.
        /// </summary>
        public static string ReconciliationAuditCorrection {
            get {
                return ResourceManager.GetString("ReconciliationAuditCorrection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Audit Corrections (previous year) ähnelt.
        /// </summary>
        public static string ReconciliationAuditCorrectionPreviousYear {
            get {
                return ResourceManager.GetString("ReconciliationAuditCorrectionPreviousYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Audit Corrections (py) ähnelt.
        /// </summary>
        public static string ReconciliationAuditCorrectionPreviousYearShort {
            get {
                return ResourceManager.GetString("ReconciliationAuditCorrectionPreviousYearShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die corrections from tax audits for previous year values ähnelt.
        /// </summary>
        public static string ReconciliationAuditCorrectionPreviousYearTooltip {
            get {
                return ResourceManager.GetString("ReconciliationAuditCorrectionPreviousYearTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Audit Corrections ähnelt.
        /// </summary>
        public static string ReconciliationAuditCorrectionShort {
            get {
                return ResourceManager.GetString("ReconciliationAuditCorrectionShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die corrections from tax audits ähnelt.
        /// </summary>
        public static string ReconciliationAuditCorrectionTooltip {
            get {
                return ResourceManager.GetString("ReconciliationAuditCorrectionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The delete of selected reconciliation was successful ähnelt.
        /// </summary>
        public static string ReconciliationDeleteSuccessful {
            get {
                return ResourceManager.GetString("ReconciliationDeleteSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Custom reconciliation ähnelt.
        /// </summary>
        public static string ReconciliationDelta {
            get {
                return ResourceManager.GetString("ReconciliationDelta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Custom ähnelt.
        /// </summary>
        public static string ReconciliationDeltaShort {
            get {
                return ResourceManager.GetString("ReconciliationDeltaShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die custom reclassification ähnelt.
        /// </summary>
        public static string ReconciliationDeltaTooltip {
            get {
                return ResourceManager.GetString("ReconciliationDeltaTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reconciliation ähnelt.
        /// </summary>
        public static string ReconciliationDialogTitle {
            get {
                return ResourceManager.GetString("ReconciliationDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File not found: {0} ähnelt.
        /// </summary>
        public static string ReconciliationFileNotFound {
            get {
                return ResourceManager.GetString("ReconciliationFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reconciliation import ähnelt.
        /// </summary>
        public static string ReconciliationImport {
            get {
                return ResourceManager.GetString("ReconciliationImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Imported values ähnelt.
        /// </summary>
        public static string ReconciliationImportedValues {
            get {
                return ResourceManager.GetString("ReconciliationImportedValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Imported values ähnelt.
        /// </summary>
        public static string ReconciliationImportedValuesShort {
            get {
                return ResourceManager.GetString("ReconciliationImportedValuesShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die imported values ähnelt.
        /// </summary>
        public static string ReconciliationImportedValuesTooltip {
            get {
                return ResourceManager.GetString("ReconciliationImportedValuesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reconciliation value import ähnelt.
        /// </summary>
        public static string ReconciliationImportValuesTitle {
            get {
                return ResourceManager.GetString("ReconciliationImportValuesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Position is selected for creating reference list ähnelt.
        /// </summary>
        public static string ReconciliationIsSelectedForReferenceListTooltip {
            get {
                return ResourceManager.GetString("ReconciliationIsSelectedForReferenceListTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die position contains reconciliation for the currently selected reconciliation dataset ähnelt.
        /// </summary>
        public static string ReconciliationIsSelectedIconTooltip {
            get {
                return ResourceManager.GetString("ReconciliationIsSelectedIconTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kind of reconciliation ähnelt.
        /// </summary>
        public static string ReconciliationKindCaption {
            get {
                return ResourceManager.GetString("ReconciliationKindCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete imported reconciliations ähnelt.
        /// </summary>
        public static string ReconciliationMenuDeleteImportedValueCaption {
            get {
                return ResourceManager.GetString("ReconciliationMenuDeleteImportedValueCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deletes all imported reconciliations ähnelt.
        /// </summary>
        public static string ReconciliationMenuDeleteImportedValueDescription {
            get {
                return ResourceManager.GetString("ReconciliationMenuDeleteImportedValueDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete previous year values ähnelt.
        /// </summary>
        public static string ReconciliationMenuDeletePreviousYearValueCaption {
            get {
                return ResourceManager.GetString("ReconciliationMenuDeletePreviousYearValueCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deletes all previous year values ähnelt.
        /// </summary>
        public static string ReconciliationMenuDeletePreviousYearValueDescription {
            get {
                return ResourceManager.GetString("ReconciliationMenuDeletePreviousYearValueDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete reconciliation ähnelt.
        /// </summary>
        public static string ReconciliationMenuDeleteReconciliationCaption {
            get {
                return ResourceManager.GetString("ReconciliationMenuDeleteReconciliationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Allows selection of one or more transactions to delete. ähnelt.
        /// </summary>
        public static string ReconciliationMenuDeleteReconciliationDescription {
            get {
                return ResourceManager.GetString("ReconciliationMenuDeleteReconciliationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import previous year values ähnelt.
        /// </summary>
        public static string ReconciliationMenuImportPreviousYearValuesCaption {
            get {
                return ResourceManager.GetString("ReconciliationMenuImportPreviousYearValuesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Allows import previous year values ähnelt.
        /// </summary>
        public static string ReconciliationMenuImportPreviousYearValuesDescription {
            get {
                return ResourceManager.GetString("ReconciliationMenuImportPreviousYearValuesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reconciliation import ähnelt.
        /// </summary>
        public static string ReconciliationMenuImportReconciliationCaption {
            get {
                return ResourceManager.GetString("ReconciliationMenuImportReconciliationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Imports reconciliation from a CSV file ähnelt.
        /// </summary>
        public static string ReconciliationMenuImportReconciliationDescription {
            get {
                return ResourceManager.GetString("ReconciliationMenuImportReconciliationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name of reconciliation ähnelt.
        /// </summary>
        public static string ReconciliationName {
            get {
                return ResourceManager.GetString("ReconciliationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Previous year values ähnelt.
        /// </summary>
        public static string ReconciliationPreviousYearValues {
            get {
                return ResourceManager.GetString("ReconciliationPreviousYearValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Previous year values ähnelt.
        /// </summary>
        public static string ReconciliationPreviousYearValuesShort {
            get {
                return ResourceManager.GetString("ReconciliationPreviousYearValuesShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Previous year values ähnelt.
        /// </summary>
        public static string ReconciliationPreviousYearValuesTooltip {
            get {
                return ResourceManager.GetString("ReconciliationPreviousYearValuesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reclassification ähnelt.
        /// </summary>
        public static string ReconciliationReclassification {
            get {
                return ResourceManager.GetString("ReconciliationReclassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Destination of the reclassification ähnelt.
        /// </summary>
        public static string ReconciliationReclassificationDest {
            get {
                return ResourceManager.GetString("ReconciliationReclassificationDest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reclassification (destination position) ähnelt.
        /// </summary>
        public static string ReconciliationReclassificationDestTooltip {
            get {
                return ResourceManager.GetString("ReconciliationReclassificationDestTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reclassification ähnelt.
        /// </summary>
        public static string ReconciliationReclassificationShort {
            get {
                return ResourceManager.GetString("ReconciliationReclassificationShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Position which should be reclassified ähnelt.
        /// </summary>
        public static string ReconciliationReclassificationSource {
            get {
                return ResourceManager.GetString("ReconciliationReclassificationSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reclassification (source position) ähnelt.
        /// </summary>
        public static string ReconciliationReclassificationSourceTooltip {
            get {
                return ResourceManager.GetString("ReconciliationReclassificationSourceTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reconciliations ähnelt.
        /// </summary>
        public static string Reconciliations {
            get {
                return ResourceManager.GetString("Reconciliations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select reconciliation type ähnelt.
        /// </summary>
        public static string ReconciliationSelectTypeCaption {
            get {
                return ResourceManager.GetString("ReconciliationSelectTypeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tax balance value ähnelt.
        /// </summary>
        public static string ReconciliationTaxBalanceValue {
            get {
                return ResourceManager.GetString("ReconciliationTaxBalanceValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tax balance value ähnelt.
        /// </summary>
        public static string ReconciliationTaxBalanceValueShort {
            get {
                return ResourceManager.GetString("ReconciliationTaxBalanceValueShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tax balance value reconciliation ähnelt.
        /// </summary>
        public static string ReconciliationTaxBalanceValueTooltip {
            get {
                return ResourceManager.GetString("ReconciliationTaxBalanceValueTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reconciliation transaction ähnelt.
        /// </summary>
        public static string ReconciliationTransaction {
            get {
                return ResourceManager.GetString("ReconciliationTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die reconciliation value ähnelt.
        /// </summary>
        public static string ReconciliationValue {
            get {
                return ResourceManager.GetString("ReconciliationValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value change ähnelt.
        /// </summary>
        public static string ReconciliationValueChange {
            get {
                return ResourceManager.GetString("ReconciliationValueChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value change ähnelt.
        /// </summary>
        public static string ReconciliationValueChangeShort {
            get {
                return ResourceManager.GetString("ReconciliationValueChangeShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die value change ähnelt.
        /// </summary>
        public static string ReconciliationValueChangeTooltip {
            get {
                return ResourceManager.GetString("ReconciliationValueChangeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No balance sheet position has been assigned. ähnelt.
        /// </summary>
        public static string ReconciliationWarningNoAssignedBalanceSheetPosition {
            get {
                return ResourceManager.GetString("ReconciliationWarningNoAssignedBalanceSheetPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No income statement position has been assigned. ähnelt.
        /// </summary>
        public static string ReconciliationWarningNoAssignedISPosition {
            get {
                return ResourceManager.GetString("ReconciliationWarningNoAssignedISPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No position has been assigned. ähnelt.
        /// </summary>
        public static string ReconciliationWarningNoAssignedPosition {
            get {
                return ResourceManager.GetString("ReconciliationWarningNoAssignedPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No assigned position is existing for this reconciliation. ähnelt.
        /// </summary>
        public static string ReconciliationWarningNoAssignedTransaction {
            get {
                return ResourceManager.GetString("ReconciliationWarningNoAssignedTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No value has been entered. ähnelt.
        /// </summary>
        public static string ReconciliationWarningNoAssignedValue {
            get {
                return ResourceManager.GetString("ReconciliationWarningNoAssignedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The assigned source position does not contain a commercial balance value. ähnelt.
        /// </summary>
        public static string ReconciliationWarningNoComercialBalanceValue {
            get {
                return ResourceManager.GetString("ReconciliationWarningNoComercialBalanceValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning within an assigned position. ähnelt.
        /// </summary>
        public static string ReconciliationWarningWarningInAssignedTransaction {
            get {
                return ResourceManager.GetString("ReconciliationWarningWarningInAssignedTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error occurred while creating the refrence list CSV ähnelt.
        /// </summary>
        public static string ReferenceListCreationError {
            get {
                return ResourceManager.GetString("ReferenceListCreationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}_Balance ähnelt.
        /// </summary>
        public static string ReferenceListFileName {
            get {
                return ResourceManager.GetString("ReferenceListFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}_ProfitAndLoss ähnelt.
        /// </summary>
        public static string ReferenceListFileNameProfitAndLoss {
            get {
                return ResourceManager.GetString("ReferenceListFileNameProfitAndLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Position description ähnelt.
        /// </summary>
        public static string ReferenceListPositionDescription {
            get {
                return ResourceManager.GetString("ReferenceListPositionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Position-ID ähnelt.
        /// </summary>
        public static string ReferenceListPositionId {
            get {
                return ResourceManager.GetString("ReferenceListPositionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Previous year value ähnelt.
        /// </summary>
        public static string ReferenceListPreviousYearValue {
            get {
                return ResourceManager.GetString("ReferenceListPreviousYearValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description ähnelt.
        /// </summary>
        public static string ReferenceListReconciliationDescription {
            get {
                return ResourceManager.GetString("ReferenceListReconciliationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name of reconciliation ähnelt.
        /// </summary>
        public static string ReferenceListReconciliationName {
            get {
                return ResourceManager.GetString("ReferenceListReconciliationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reconciliation value ähnelt.
        /// </summary>
        public static string ReferenceListReconciliationValue {
            get {
                return ResourceManager.GetString("ReferenceListReconciliationValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tax value ähnelt.
        /// </summary>
        public static string ReferenceListTaxValue {
            get {
                return ResourceManager.GetString("ReferenceListTaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Balance value ähnelt.
        /// </summary>
        public static string ReferenceListValue {
            get {
                return ResourceManager.GetString("ReferenceListValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Really delete all previous year correction values? ähnelt.
        /// </summary>
        public static string RequestDeleteAllPreviousYearCorrectionValues {
            get {
                return ResourceManager.GetString("RequestDeleteAllPreviousYearCorrectionValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Really delete all previous year values? ähnelt.
        /// </summary>
        public static string RequestDeleteAllPreviousYearValues {
            get {
                return ResourceManager.GetString("RequestDeleteAllPreviousYearValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Removing input values are not allowed! ähnelt.
        /// </summary>
        public static string RequestDeleteImportedValueNotAllowed {
            get {
                return ResourceManager.GetString("RequestDeleteImportedValueNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Really remove reconciliation for position &quot;{0}&quot;? ähnelt.
        /// </summary>
        public static string RequestDeletePosition {
            get {
                return ResourceManager.GetString("RequestDeletePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Really remove previous year correction value for position &quot;{0}&quot;? ähnelt.
        /// </summary>
        public static string RequestDeletePreviousYearCorrectionValue {
            get {
                return ResourceManager.GetString("RequestDeletePreviousYearCorrectionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Really remove previous year value for position &quot;{0}&quot;? ähnelt.
        /// </summary>
        public static string RequestDeletePreviousYearValue {
            get {
                return ResourceManager.GetString("RequestDeletePreviousYearValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Really remove reconciliation dataset &quot;{0}&quot;? ähnelt.
        /// </summary>
        public static string RequestDeleteReconciliation {
            get {
                return ResourceManager.GetString("RequestDeleteReconciliation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not save reconciliation dataset:  ähnelt.
        /// </summary>
        public static string SaveException {
            get {
                return ResourceManager.GetString("SaveException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not save transaction:  ähnelt.
        /// </summary>
        public static string SaveTransactionException {
            get {
                return ResourceManager.GetString("SaveTransactionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select previous year report ähnelt.
        /// </summary>
        public static string SelectedPreviousYearReport {
            get {
                return ResourceManager.GetString("SelectedPreviousYearReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select previous year report ähnelt.
        /// </summary>
        public static string SelectPreviousYearReport {
            get {
                return ResourceManager.GetString("SelectPreviousYearReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Assign position using drag and drop ähnelt.
        /// </summary>
        public static string SetPosPerDragAndDrop {
            get {
                return ResourceManager.GetString("SetPosPerDragAndDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die enter amount and comment ähnelt.
        /// </summary>
        public static string SetReconciliationAmountAndComment {
            get {
                return ResourceManager.GetString("SetReconciliationAmountAndComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die enter comment ähnelt.
        /// </summary>
        public static string SetReconciliationComment {
            get {
                return ResourceManager.GetString("SetReconciliationComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die set destination of the reclassification ähnelt.
        /// </summary>
        public static string SetReconciliationReclassificationDest {
            get {
                return ResourceManager.GetString("SetReconciliationReclassificationDest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die set position which should be reclassified ähnelt.
        /// </summary>
        public static string SetReconciliationReclassificationSource {
            get {
                return ResourceManager.GetString("SetReconciliationReclassificationSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show commercial balance values ähnelt.
        /// </summary>
        public static string ShowCommercialBalanceValues {
            get {
                return ResourceManager.GetString("ShowCommercialBalanceValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter previous year values ähnelt.
        /// </summary>
        public static string ShowEnterPreviousYearValuesTextbox {
            get {
                return ResourceManager.GetString("ShowEnterPreviousYearValuesTextbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show reconciliation values ähnelt.
        /// </summary>
        public static string ShowReconciliationValues {
            get {
                return ResourceManager.GetString("ShowReconciliationValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show tax balance values ähnelt.
        /// </summary>
        public static string ShowTaxBalanceValues {
            get {
                return ResourceManager.GetString("ShowTaxBalanceValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die sum:  ähnelt.
        /// </summary>
        public static string Sum {
            get {
                return ResourceManager.GetString("Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Summary ähnelt.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sum:  ähnelt.
        /// </summary>
        public static string TabHeaderSumCaption {
            get {
                return ResourceManager.GetString("TabHeaderSumCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die tax balance value ähnelt.
        /// </summary>
        public static string TaxBalanceValue {
            get {
                return ResourceManager.GetString("TaxBalanceValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die It is not possible to assign more than one balance sheet position to a value change reconciliation. ähnelt.
        /// </summary>
        public static string TransactionAssignmentErrorOnlyOneBalanceSheetPosAllowed {
            get {
                return ResourceManager.GetString("TransactionAssignmentErrorOnlyOneBalanceSheetPosAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not assign position because it is already assigned to the current reconciliation ähnelt.
        /// </summary>
        public static string TransactionAssignmentErrorPositionIsAlreadyAssigned {
            get {
                return ResourceManager.GetString("TransactionAssignmentErrorPositionIsAlreadyAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not assign position because it is already assigned as source for a reclassification. ähnelt.
        /// </summary>
        public static string TransactionAssignmentErrorPositionIsReclassificationSource {
            get {
                return ResourceManager.GetString("TransactionAssignmentErrorPositionIsReclassificationSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Source and destination of the reclassification must both be contained in the same balance sheet side (assets, libilities) or both contained in the income statement. ähnelt.
        /// </summary>
        public static string TransactionAssignmentErrorReclassivicationIllegalGroup {
            get {
                return ResourceManager.GetString("TransactionAssignmentErrorReclassivicationIllegalGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value change ähnelt.
        /// </summary>
        public static string TransferKindChangeVlaue {
            get {
                return ResourceManager.GetString("TransferKindChangeVlaue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Transfer kind conversion error ähnelt.
        /// </summary>
        public static string TransferKindError {
            get {
                return ResourceManager.GetString("TransferKindError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reclassification ähnelt.
        /// </summary>
        public static string TransferKindReclassification {
            get {
                return ResourceManager.GetString("TransferKindReclassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reclassification with value change ähnelt.
        /// </summary>
        public static string TransferKindReclassificationChangeValue {
            get {
                return ResourceManager.GetString("TransferKindReclassificationChangeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Type of reconciliation ähnelt.
        /// </summary>
        public static string TypeOfReconciliation {
            get {
                return ResourceManager.GetString("TypeOfReconciliation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown file format ähnelt.
        /// </summary>
        public static string UnknownFileFormat {
            get {
                return ResourceManager.GetString("UnknownFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update reconciliation ähnelt.
        /// </summary>
        public static string UpdateReconciliation {
            get {
                return ResourceManager.GetString("UpdateReconciliation", resourceCulture);
            }
        }
    }
}
