//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.269
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBalanceKitResources.Localisation {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcesValidationErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesValidationErrors() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eBalanceKitResources.Localisation.ResourcesValidationErrors", typeof(ResourcesValidationErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Total assets and total equity and liabilities are not equal. ähnelt.
        /// </summary>
        public static string Aktiva_differs_Passiva {
            get {
                return ResourceManager.GetString("Aktiva_differs_Passiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aktiva und Passiva stimmen nach Anwendung der Überleitungsrechnung nicht überein. ähnelt.
        /// </summary>
        public static string Aktiva_differs_Passiva_Recon {
            get {
                return ResourceManager.GetString("Aktiva_differs_Passiva_Recon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die At a final annual balance sheet the balance sheet closing date has to be equal the end of the fiscal year. ähnelt.
        /// </summary>
        public static string balSheetClosingDate_not_equals_fiscalYearEnd {
            get {
                return ResourceManager.GetString("balSheetClosingDate_not_equals_fiscalYearEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es wurde eine Handelsbilanz ausgewählt, aber kein Überleitungswert eingetragen. ähnelt.
        /// </summary>
        public static string CommercialBalanceSheetWithoutReconciliations {
            get {
                return ResourceManager.GetString("CommercialBalanceSheetWithoutReconciliations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die empty report parts are not allowed to send ähnelt.
        /// </summary>
        public static string EmptyReportPart {
            get {
                return ResourceManager.GetString("EmptyReportPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Accounting standards has not yet been specified. ähnelt.
        /// </summary>
        public static string gcd_genInfo_report_id_accountingStandard {
            get {
                return ResourceManager.GetString("gcd_genInfo_report_id_accountingStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die date required ähnelt.
        /// </summary>
        public static string GcdFiscalYearBeginNotExists {
            get {
                return ResourceManager.GetString("GcdFiscalYearBeginNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die date required ähnelt.
        /// </summary>
        public static string GcdFiscalYearEndNotExists {
            get {
                return ResourceManager.GetString("GcdFiscalYearEndNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If using TC it is not allowed to enter a value at operating result (CoS). ähnelt.
        /// </summary>
        public static string GKV_and_operatingCOGS {
            get {
                return ResourceManager.GetString("GKV_and_operatingCOGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} has to be equal {1} ähnelt.
        /// </summary>
        public static string HasToBeEqual {
            get {
                return ResourceManager.GetString("HasToBeEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If value for {0} there must be a value for {1}. ähnelt.
        /// </summary>
        public static string IfThenRequired {
            get {
                return ResourceManager.GetString("IfThenRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wenn die Bilanz den Ausweis des Bilanzgewinns enthält, muss der Berichtsbestandteil Ergebnisverwendung übermittelt werden. ähnelt.
        /// </summary>
        public static string IncomeStatementendswithBalProfitRequiresIncomeUse {
            get {
                return ResourceManager.GetString("IncomeStatementendswithBalProfitRequiresIncomeUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es müssen alle oder keine Informationen zum Wirtschaftszweig angegeben werden. ähnelt.
        /// </summary>
        public static string IndustrySectorAllOrNone {
            get {
                return ResourceManager.GetString("IndustrySectorAllOrNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The selected legal status is not allowed. ähnelt.
        /// </summary>
        public static string legalStatusNotAllowed {
            get {
                return ResourceManager.GetString("legalStatusNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Net income/net loss for the financial year in Appropriation of net profit and balance are not equal. ähnelt.
        /// </summary>
        public static string netIncome_GuV_differs_IncomeUse {
            get {
                return ResourceManager.GetString("netIncome_GuV_differs_IncomeUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die no account assigned or not sending any account balance information ähnelt.
        /// </summary>
        public static string NoAccountAssigned {
            get {
                return ResourceManager.GetString("NoAccountAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bei steuerlich unzulässigen Positionen darf kein Wert berichtet werden bei Einreichung einer Steuerbilanz. ähnelt.
        /// </summary>
        public static string NotAllowedForTax {
            get {
                return ResourceManager.GetString("NotAllowedForTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bei steuerlich unzulässigen Positionen muss der Steuerbilanzwert 0,00€ ergeben. ähnelt.
        /// </summary>
        public static string NotAllowedForTaxCommercialBalanceSheet {
            get {
                return ResourceManager.GetString("NotAllowedForTaxCommercialBalanceSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This information is not allowed at submissions to the fiscal authority. ähnelt.
        /// </summary>
        public static string NotPermittedForFinancial {
            get {
                return ResourceManager.GetString("NotPermittedForFinancial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This selection is not allowed at submissions to the fiscal authority. ähnelt.
        /// </summary>
        public static string NotPermittedForFinancial_Selection {
            get {
                return ResourceManager.GetString("NotPermittedForFinancial_Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Net retained profits/net accumulated losses in Appropriation of net profit and balance are not equal. ähnelt.
        /// </summary>
        public static string profitLoss_unequal_gainLoss {
            get {
                return ResourceManager.GetString("profitLoss_unequal_gainLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Überleitung an dieser Stelle nicht erlaubt, da bereits eine Überleitung an einem Ober-/Unterpunkt eingegeben wurde. ähnelt.
        /// </summary>
        public static string ReconciliationNotAllowed {
            get {
                return ResourceManager.GetString("ReconciliationNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This report part was filled but not selected for sending. ähnelt.
        /// </summary>
        public static string ReportPartFilledButNotSelected {
            get {
                return ResourceManager.GetString("ReportPartFilledButNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Marked taxonomy position with SendAccountDetails but not selected report part AccountDetails ähnelt.
        /// </summary>
        public static string SendAccountDetailsInconsistency {
            get {
                return ResourceManager.GetString("SendAccountDetailsInconsistency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If using CoS it is not allowed to enter a value at operating result (TC). ähnelt.
        /// </summary>
        public static string UKV_and_operatingTC {
            get {
                return ResourceManager.GetString("UKV_and_operatingTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select an income statement format. ähnelt.
        /// </summary>
        public static string unallowedIncomeStatementFormat {
            get {
                return ResourceManager.GetString("unallowedIncomeStatementFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If the report is a annual financial statement you have to insert a date. ähnelt.
        /// </summary>
        public static string ValidatorGCD_Validate_Bei_einem_endgültigen_Jahresabschluss_muss_ein_Datum_angegeben_werden_ {
            get {
                return ResourceManager.GetString("ValidatorGCD_Validate_Bei_einem_endgültigen_Jahresabschluss_muss_ein_Datum_angege" +
                        "ben_werden_", resourceCulture);
            }
        }
    }
}
