//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.296
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBalanceKitResources.Localisation {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcesFederalGazetteParameters {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesFederalGazetteParameters() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eBalanceKitResources.Localisation.ResourcesFederalGazetteParameters", typeof(ResourcesFederalGazetteParameters).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pflichtfeld in der Rubrik 14, Veröffentlichungsart 135, Veröffentlichungstypen 3 oder
        ///5. ähnelt.
        /// </summary>
        public static string Error_BalanceSheetStandard {
            get {
                return ResourceManager.GetString("Error_BalanceSheetStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Datum muss in der Zukunft liegen, auf einen Arbeitstag fallen und darf nicht
        ///mehr als ein Jahr nach dem Geschäftsjahres-bis Datum liegen
        ///Dieses muss leer sein, wenn nicht in der Rubrik 14, Veröffentlichungsart 135 und
        ///Veröffentlichungstypen 3 oder 5 bzw. Rubrik 14 und Veröffentlichungsart 86 ähnelt.
        /// </summary>
        public static string Error_BlockingDate {
            get {
                return ResourceManager.GetString("Error_BlockingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pflichtfeld in der Rubrik 14, Veröffentlichungsart 135, Veröffentlichungstypen 3 oder
        ///5 sowie in der Rubrik 90, Veröffentlichungsart 136 oder 138. ähnelt.
        /// </summary>
        public static string Error_CompanySize {
            get {
                return ResourceManager.GetString("Error_CompanySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pflichtfeld in der Rubrik 14, Veröffentlichungsart 135, Veröffentlichungstypen 3 oder
        ///5 sowie in der Rubrik 90, Veröffentlichungsart 136 oder 138. ähnelt.
        /// </summary>
        public static string Error_CompanyType {
            get {
                return ResourceManager.GetString("Error_CompanyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &apos;{0}&apos; muss einen Wert haben ähnelt.
        /// </summary>
        public static string Error_MustHaveValue {
            get {
                return ResourceManager.GetString("Error_MustHaveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pflichtfeld in der Rubrik 14 und Veröffentlichungsart 135, 121 und 139. ähnelt.
        /// </summary>
        public static string Error_PublicationSubType {
            get {
                return ResourceManager.GetString("Error_PublicationSubType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pflichtfeld in der Rubrik 14 und Veröffentlichungsart 86. ähnelt.
        /// </summary>
        public static string Error_SubmitterType {
            get {
                return ResourceManager.GetString("Error_SubmitterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ende des Bezugszeitraums ähnelt.
        /// </summary>
        public static string Parameter_AcquisitationPeriodEnd {
            get {
                return ResourceManager.GetString("Parameter_AcquisitationPeriodEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beginn des Bezugszeitraums ähnelt.
        /// </summary>
        public static string Parameter_AcquisitationPeriodStart {
            get {
                return ResourceManager.GetString("Parameter_AcquisitationPeriodStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Umfang der Einreichung ähnelt.
        /// </summary>
        public static string Parameter_AnnualContentType {
            get {
                return ResourceManager.GetString("Parameter_AnnualContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bilanzierungsstandard ähnelt.
        /// </summary>
        public static string Parameter_BalanceSheetStandard {
            get {
                return ResourceManager.GetString("Parameter_BalanceSheetStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sperrfrist-Datum ähnelt.
        /// </summary>
        public static string Parameter_BlockingDate {
            get {
                return ResourceManager.GetString("Parameter_BlockingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Größe des Unternehmens ähnelt.
        /// </summary>
        public static string Parameter_CompanySize {
            get {
                return ResourceManager.GetString("Parameter_CompanySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Art der Gesellschaft ähnelt.
        /// </summary>
        public static string Parameter_CompanyType {
            get {
                return ResourceManager.GetString("Parameter_CompanyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Gesellschaft hat eine oder mehrere natürliche Personen als Gesellschafter ähnelt.
        /// </summary>
        public static string Parameter_HasNaturalPerson {
            get {
                return ResourceManager.GetString("Parameter_HasNaturalPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Art des Auftrags ähnelt.
        /// </summary>
        public static string Parameter_OrderTypes {
            get {
                return ResourceManager.GetString("Parameter_OrderTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichungsbereich ähnelt.
        /// </summary>
        public static string Parameter_PublicationArea {
            get {
                return ResourceManager.GetString("Parameter_PublicationArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichungsrubrik ähnelt.
        /// </summary>
        public static string Parameter_PublicationCategory {
            get {
                return ResourceManager.GetString("Parameter_PublicationCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sprache der Bekanntmachung ähnelt.
        /// </summary>
        public static string Parameter_PublicationLanguage {
            get {
                return ResourceManager.GetString("Parameter_PublicationLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichungstyp ähnelt.
        /// </summary>
        public static string Parameter_PublicationSubType {
            get {
                return ResourceManager.GetString("Parameter_PublicationSubType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichungsart ähnelt.
        /// </summary>
        public static string Parameter_PublicationType {
            get {
                return ResourceManager.GetString("Parameter_PublicationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Typ der Gesellschaft ähnelt.
        /// </summary>
        public static string Parameter_SubmitterType {
            get {
                return ResourceManager.GetString("Parameter_SubmitterType", resourceCulture);
            }
        }
    }
}
