//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.269
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBalanceKitResources.Localisation {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcesHyperCube {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesHyperCube() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eBalanceKitResources.Localisation.ResourcesHyperCube", typeof(ResourcesHyperCube).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto calculated value:  ähnelt.
        /// </summary>
        public static string AutoValue {
            get {
                return ResourceManager.GetString("AutoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die import ähnelt.
        /// </summary>
        public static string btImport {
            get {
                return ResourceManager.GetString("btImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save template ähnelt.
        /// </summary>
        public static string btSave {
            get {
                return ResourceManager.GetString("btSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General ähnelt.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        public static string HyperCubeColumnCaption {
            get {
                return ResourceManager.GetString("HyperCubeColumnCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        public static string HyperCubeRowCaption {
            get {
                return ResourceManager.GetString("HyperCubeRowCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last modified by {0} at {1} {2} ähnelt.
        /// </summary>
        public static string LastModified {
            get {
                return ResourceManager.GetString("LastModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        public static string lbAssignment {
            get {
                return ResourceManager.GetString("lbAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beschreibung ähnelt.
        /// </summary>
        public static string lblTemplateDescription {
            get {
                return ResourceManager.GetString("lblTemplateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die template name ähnelt.
        /// </summary>
        public static string lblTemplateName {
            get {
                return ResourceManager.GetString("lblTemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Template must be generated ähnelt.
        /// </summary>
        public static string MsgTemplateCreation {
            get {
                return ResourceManager.GetString("MsgTemplateCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Summary ähnelt.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select your CSV file ähnelt.
        /// </summary>
        public static string tbFileSelection {
            get {
                return ResourceManager.GetString("tbFileSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Column assignment ähnelt.
        /// </summary>
        public static string tbHeaderColumnAssignment {
            get {
                return ResourceManager.GetString("tbHeaderColumnAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die configuration of the CSV structure ähnelt.
        /// </summary>
        public static string tbHeaderCsvConfig {
            get {
                return ResourceManager.GetString("tbHeaderCsvConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import preview ähnelt.
        /// </summary>
        public static string tbHeaderImportPreview {
            get {
                return ResourceManager.GetString("tbHeaderImportPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import summary ähnelt.
        /// </summary>
        public static string tbHeaderImportSummary {
            get {
                return ResourceManager.GetString("tbHeaderImportSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Row assignment ähnelt.
        /// </summary>
        public static string tbHeaderRowAssignment {
            get {
                return ResourceManager.GetString("tbHeaderRowAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die basic data for the Template ähnelt.
        /// </summary>
        public static string tbHeaderTemplateData {
            get {
                return ResourceManager.GetString("tbHeaderTemplateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die choose a template (or create a new one) ähnelt.
        /// </summary>
        public static string tbHeaderTemplateSelection {
            get {
                return ResourceManager.GetString("tbHeaderTemplateSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Template summary ähnelt.
        /// </summary>
        public static string tbHeaderTemplateSummary {
            get {
                return ResourceManager.GetString("tbHeaderTemplateSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preview (max. 50 lines visible) ähnelt.
        /// </summary>
        public static string txtPreviewData {
            get {
                return ResourceManager.GetString("txtPreviewData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import with Problems ähnelt.
        /// </summary>
        public static string txtSummaryFailed {
            get {
                return ResourceManager.GetString("txtSummaryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import OK ähnelt.
        /// </summary>
        public static string txtSummarySuccess {
            get {
                return ResourceManager.GetString("txtSummarySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your value (CSV):  ähnelt.
        /// </summary>
        public static string YourValue {
            get {
                return ResourceManager.GetString("YourValue", resourceCulture);
            }
        }
    }
}
