//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBalanceKitResources.Localisation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcesExampleCompanyData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesExampleCompanyData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eBalanceKitResources.Localisation.ResourcesExampleCompanyData", typeof(ResourcesExampleCompanyData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact 1.
        /// </summary>
        public static string genInfo_company_id_contactAddress_person {
            get {
                return ResourceManager.GetString("genInfo_company_id_contactAddress_person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact 2.
        /// </summary>
        public static string genInfo_company_id_contactAddress_person__2__ {
            get {
                return ResourceManager.GetString("genInfo_company_id_contactAddress_person__2__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the contactperson.
        /// </summary>
        public static string genInfo_company_id_contactAddress_person_name {
            get {
                return ResourceManager.GetString("genInfo_company_id_contactAddress_person_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the contactperson 2.
        /// </summary>
        public static string genInfo_company_id_contactAddress_person_name__2__ {
            get {
                return ResourceManager.GetString("genInfo_company_id_contactAddress_person_name__2__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example company.
        /// </summary>
        public static string genInfo_company_id_name {
            get {
                return ResourceManager.GetString("genInfo_company_id_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 03.12.2012.
        /// </summary>
        public static string genInfo_company_id_name_dateOfLastChange {
            get {
                return ResourceManager.GetString("genInfo_company_id_name_dateOfLastChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 03.12.2012.
        /// </summary>
        public static string genInfo_company_id_parent_legalStatus_dateOfLastChange {
            get {
                return ResourceManager.GetString("genInfo_company_id_parent_legalStatus_dateOfLastChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 04.12.2012.
        /// </summary>
        public static string genInfo_company_id_parent_name_dateOfLastChange {
            get {
                return ResourceManager.GetString("genInfo_company_id_parent_name_dateOfLastChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shareholder name.
        /// </summary>
        public static string genInfo_company_id_shareholder_name {
            get {
                return ResourceManager.GetString("genInfo_company_id_shareholder_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shareholder name 2.
        /// </summary>
        public static string genInfo_company_id_shareholder_name__2__ {
            get {
                return ResourceManager.GetString("genInfo_company_id_shareholder_name__2__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        public static string genInfo_company_id_shareholder_SpecialBalanceRequired {
            get {
                return ResourceManager.GetString("genInfo_company_id_shareholder_SpecialBalanceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        public static string genInfo_company_id_shareholder_SpecialBalanceRequired__2__ {
            get {
                return ResourceManager.GetString("genInfo_company_id_shareholder_SpecialBalanceRequired__2__", resourceCulture);
            }
        }
    }
}
