//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBalanceKitResources.Localisation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcesPdfExport {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesPdfExport() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eBalanceKitResources.Localisation.ResourcesPdfExport", typeof(ResourcesPdfExport).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of actual year.
        /// </summary>
        public static string ActualYearValue {
            get {
                return ResourceManager.GetString("ActualYearValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comment :.
        /// </summary>
        public static string CommentLabel {
            get {
                return ResourceManager.GetString("CommentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export like Xbrl.
        /// </summary>
        public static string ExportAsXbrlComboText {
            get {
                return ResourceManager.GetString("ExportAsXbrlComboText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrying amount in financial statements.
        /// </summary>
        public static string Handelsbilanzwert {
            get {
                return ResourceManager.GetString("Handelsbilanzwert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select file destination.
        /// </summary>
        public static string HeaderSelectFileDestination {
            get {
                return ResourceManager.GetString("HeaderSelectFileDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (not send).
        /// </summary>
        public static string NotSend {
            get {
                return ResourceManager.GetString("NotSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconciliation current / previous period.
        /// </summary>
        public static string ReconciliationCurPer {
            get {
                return ResourceManager.GetString("ReconciliationCurPer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of reconciliation: .
        /// </summary>
        public static string ReconciliationType {
            get {
                return ResourceManager.GetString("ReconciliationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax base.
        /// </summary>
        public static string Steuerbilanzwert {
            get {
                return ResourceManager.GetString("Steuerbilanzwert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconciliation (amount).
        /// </summary>
        public static string Überleitungswert {
            get {
                return ResourceManager.GetString("Überleitungswert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unassigned accounts.
        /// </summary>
        public static string UnassignedAccounts {
            get {
                return ResourceManager.GetString("UnassignedAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  with balances.
        /// </summary>
        public static string WithBalances {
            get {
                return ResourceManager.GetString("WithBalances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export unassigned accounts.
        /// </summary>
        public static string WithUnassignedAccounts {
            get {
                return ResourceManager.GetString("WithUnassignedAccounts", resourceCulture);
            }
        }
    }
}
