//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBalanceKitResources.Localisation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcesTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eBalanceKitResources.Localisation.ResourcesTemplates", typeof(ResourcesTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} account(s).
        /// </summary>
        public static string AccountAmount {
            get {
                return ResourceManager.GetString("AccountAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} account group(s).
        /// </summary>
        public static string AccountGroupAmount {
            get {
                return ResourceManager.GetString("AccountGroupAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorlage auf folgende Summen- und Saldenlisten anwenden:.
        /// </summary>
        public static string BalanceListForTemplateCaption {
            get {
                return ResourceManager.GetString("BalanceListForTemplateCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to overwrite option &quot;sum up positions without defined computation rules&quot;?.
        /// </summary>
        public static string ChkReplaceAutoComputeEnabledFlagCaption {
            get {
                return ResourceManager.GetString("ChkReplaceAutoComputeEnabledFlagCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to overwrite option &quot;ignor warning message&quot;?.
        /// </summary>
        public static string ChkReplaceIgnoreWarningMessageFlagCaption {
            get {
                return ResourceManager.GetString("ChkReplaceIgnoreWarningMessageFlagCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to overwrite option &quot;send account balances&quot;?.
        /// </summary>
        public static string ChkReplaceSendAccountBalanceFlagCaption {
            get {
                return ResourceManager.GetString("ChkReplaceSendAccountBalanceFlagCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All of the accounts for that template are already assigned, or missing from that balance list..
        /// </summary>
        public static string DisabledButtonToolTip {
            get {
                return ResourceManager.GetString("DisabledButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} von {1} Konten (gefiltert).
        /// </summary>
        public static string FilteredAccountString {
            get {
                return ResourceManager.GetString("FilteredAccountString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account list filter.
        /// </summary>
        public static string FilterToolTip {
            get {
                return ResourceManager.GetString("FilterToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Grouping.
        /// </summary>
        public static string GroupingTitle {
            get {
                return ResourceManager.GetString("GroupingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no account is available.
        /// </summary>
        public static string NoAccount {
            get {
                return ResourceManager.GetString("NoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no accounts are assigned.
        /// </summary>
        public static string NoAccountAssigned {
            get {
                return ResourceManager.GetString("NoAccountAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no account group is available.
        /// </summary>
        public static string NoAccountGroup {
            get {
                return ResourceManager.GetString("NoAccountGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to number of grouped account: .
        /// </summary>
        public static string NumberOfAccountsCaption {
            get {
                return ResourceManager.GetString("NumberOfAccountsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account sorting.
        /// </summary>
        public static string SortToolTip {
            get {
                return ResourceManager.GetString("SortToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template: .
        /// </summary>
        public static string TemplateCaption {
            get {
                return ResourceManager.GetString("TemplateCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following accounts are already assigned or missing from the actual balance list, but they are existing in the template.
        /// </summary>
        public static string ToolTipTitleForMissingChilds {
            get {
                return ResourceManager.GetString("ToolTipTitleForMissingChilds", resourceCulture);
            }
        }
    }
}
