//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.296
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBalanceKitResources.Localisation {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcesFederalGazette {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesFederalGazette() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eBalanceKitResources.Localisation.ResourcesFederalGazette", typeof(ResourcesFederalGazette).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Assistant for transfering information to the federal gazette ähnelt.
        /// </summary>
        public static string AssistantTooltip {
            get {
                return ResourceManager.GetString("AssistantTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sending data to the federal gazette is only allowed for closed business years. ähnelt.
        /// </summary>
        public static string BalanceClosingDateIssue {
            get {
                return ResourceManager.GetString("BalanceClosingDateIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Client list ähnelt.
        /// </summary>
        public static string ClientList {
            get {
                return ResourceManager.GetString("ClientList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Company size: ähnelt.
        /// </summary>
        public static string ConfigCompanySize {
            get {
                return ResourceManager.GetString("ConfigCompanySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Large company (§267 HGB). ähnelt.
        /// </summary>
        public static string ConfigCompanySizeLargeToolTip {
            get {
                return ResourceManager.GetString("ConfigCompanySizeLargeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Medium company (§267 HGB). ähnelt.
        /// </summary>
        public static string ConfigCompanySizeMediumToolTip {
            get {
                return ResourceManager.GetString("ConfigCompanySizeMediumToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Small company (§267 HGB). ähnelt.
        /// </summary>
        public static string ConfigCompanySizeSmallToolTip {
            get {
                return ResourceManager.GetString("ConfigCompanySizeSmallToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select the size of your company ähnelt.
        /// </summary>
        public static string ConfigTitle {
            get {
                return ResourceManager.GetString("ConfigTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The webservice of the federal gazette responded to the current request with the following message: ähnelt.
        /// </summary>
        public static string ErrorOfWebservice {
            get {
                return ResourceManager.GetString("ErrorOfWebservice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export as PDF ähnelt.
        /// </summary>
        public static string ExportButton {
            get {
                return ResourceManager.GetString("ExportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Federal gazette ähnelt.
        /// </summary>
        public static string FederalGazette {
            get {
                return ResourceManager.GetString("FederalGazette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Terms of service ähnelt.
        /// </summary>
        public static string HeaderTos {
            get {
                return ResourceManager.GetString("HeaderTos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Large ähnelt.
        /// </summary>
        public static string Large {
            get {
                return ResourceManager.GetString("Large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Medium ähnelt.
        /// </summary>
        public static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copying values ähnelt.
        /// </summary>
        public static string OvertakeDataCaption {
            get {
                return ResourceManager.GetString("OvertakeDataCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die to transfer the values from the E-Balance report to the report for the federal gazette? ähnelt.
        /// </summary>
        public static string OvertakeDataQuestion {
            get {
                return ResourceManager.GetString("OvertakeDataQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to retrieve the data. ähnelt.
        /// </summary>
        public static string PreviewNoData {
            get {
                return ResourceManager.GetString("PreviewNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preview not available ähnelt.
        /// </summary>
        public static string PreviewNotAvailable {
            get {
                return ResourceManager.GetString("PreviewNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loading data from federal gazette ... ähnelt.
        /// </summary>
        public static string ProgressCaptionLoading {
            get {
                return ResourceManager.GetString("ProgressCaptionLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die read companies ähnelt.
        /// </summary>
        public static string ReadCompanies {
            get {
                return ResourceManager.GetString("ReadCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Small ähnelt.
        /// </summary>
        public static string Small {
            get {
                return ResourceManager.GetString("Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Notes ähnelt.
        /// </summary>
        public static string TabAnhangHeader {
            get {
                return ResourceManager.GetString("TabAnhangHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Balance ähnelt.
        /// </summary>
        public static string TabBilanzHeader {
            get {
                return ResourceManager.GetString("TabBilanzHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Company Size ähnelt.
        /// </summary>
        public static string TabCompanySizeHeader {
            get {
                return ResourceManager.GetString("TabCompanySizeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Income Statement ähnelt.
        /// </summary>
        public static string TabGuVHeader {
            get {
                return ResourceManager.GetString("TabGuVHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Management report ähnelt.
        /// </summary>
        public static string TabLageberichtHeader {
            get {
                return ResourceManager.GetString("TabLageberichtHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Notes ähnelt.
        /// </summary>
        public static string TabReportOptionsColAnhang {
            get {
                return ResourceManager.GetString("TabReportOptionsColAnhang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Balance ähnelt.
        /// </summary>
        public static string TabReportOptionsColBilanz {
            get {
                return ResourceManager.GetString("TabReportOptionsColBilanz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Income Statement ähnelt.
        /// </summary>
        public static string TabReportOptionsColGuv {
            get {
                return ResourceManager.GetString("TabReportOptionsColGuv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Management report ähnelt.
        /// </summary>
        public static string TabReportOptionsColLagebericht {
            get {
                return ResourceManager.GetString("TabReportOptionsColLagebericht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Report part ähnelt.
        /// </summary>
        public static string TabReportOptionsColReportHeader {
            get {
                return ResourceManager.GetString("TabReportOptionsColReportHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sending? ähnelt.
        /// </summary>
        public static string TabReportOptionsColValueHeader {
            get {
                return ResourceManager.GetString("TabReportOptionsColValueHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Report options ähnelt.
        /// </summary>
        public static string TabReportOptionsHeader {
            get {
                return ResourceManager.GetString("TabReportOptionsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Below you have to confirm that you have read and understood the &apos;General Terms and Conditions for Paid Submission and Publication in the “Bundesanzeiger&quot; (federal gazette)&apos;.
        ///The up-to-date terms of services you can find online at http://www.bundesanzeiger.de/agb ähnelt.
        /// </summary>
        public static string TosHint {
            get {
                return ResourceManager.GetString("TosHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die I accept the TOS of the federal gazette ähnelt.
        /// </summary>
        public static string TosQuery {
            get {
                return ResourceManager.GetString("TosQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die eBalance-Kit / Federal gazette assistant ähnelt.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
