//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.544
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBalanceKitResources.Localisation {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcesCommon {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesCommon() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eBalanceKitResources.Localisation.ResourcesCommon", typeof(ResourcesCommon).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Accept ähnelt.
        /// </summary>
        public static string AcceptChanges {
            get {
                return ResourceManager.GetString("AcceptChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Account is selected for creating reference list ähnelt.
        /// </summary>
        public static string AccountIsSelectedForReferenceListTooltip {
            get {
                return ResourceManager.GetString("AccountIsSelectedForReferenceListTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Accounts reference List ähnelt.
        /// </summary>
        public static string AccountsReferenceList {
            get {
                return ResourceManager.GetString("AccountsReferenceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die account structure ähnelt.
        /// </summary>
        public static string AccountStructure {
            get {
                return ResourceManager.GetString("AccountStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Active ähnelt.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die active directory user (user from windows login) ähnelt.
        /// </summary>
        public static string ActiveDirectioryUserTooltip {
            get {
                return ResourceManager.GetString("ActiveDirectioryUserTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Active Directory ähnelt.
        /// </summary>
        public static string ActiveDirectory {
            get {
                return ResourceManager.GetString("ActiveDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add CSV Files ähnelt.
        /// </summary>
        public static string AddCsvFileButton {
            get {
                return ResourceManager.GetString("AddCsvFileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add new user role (INS) ähnelt.
        /// </summary>
        public static string AddRoleTooltip {
            get {
                return ResourceManager.GetString("AddRoleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import new user from Active Directory (F5) ähnelt.
        /// </summary>
        public static string AddUserADTooltip {
            get {
                return ResourceManager.GetString("AddUserADTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add new user (INS) ähnelt.
        /// </summary>
        public static string AddUserTooltip {
            get {
                return ResourceManager.GetString("AddUserTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Administrator ähnelt.
        /// </summary>
        public static string Administrator {
            get {
                return ResourceManager.GetString("Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die allowed due to administrator rights ähnelt.
        /// </summary>
        public static string AllowedDueToAdminRights {
            get {
                return ResourceManager.GetString("AllowedDueToAdminRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die and ähnelt.
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apply filter ähnelt.
        /// </summary>
        public static string ApplyFilterToolTip {
            get {
                return ResourceManager.GetString("ApplyFilterToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apply template ähnelt.
        /// </summary>
        public static string ApplyTemplate {
            get {
                return ResourceManager.GetString("ApplyTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Administered Company ähnelt.
        /// </summary>
        public static string AssignedCompanies {
            get {
                return ResourceManager.GetString("AssignedCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die NavigateBack ähnelt.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die balance - assets ähnelt.
        /// </summary>
        public static string BalanceAssets {
            get {
                return ResourceManager.GetString("BalanceAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die balance - liabilites ähnelt.
        /// </summary>
        public static string BalanceLiabilities {
            get {
                return ResourceManager.GetString("BalanceLiabilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The difference between Total assets and Total equity and liabilities is ähnelt.
        /// </summary>
        public static string BalanceSheetSaldoDifferenceString {
            get {
                return ResourceManager.GetString("BalanceSheetSaldoDifferenceString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Help ähnelt.
        /// </summary>
        public static string btHelp {
            get {
                return ResourceManager.GetString("btHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die apply selected template ähnelt.
        /// </summary>
        public static string BtnApplyTemplateTooltip {
            get {
                return ResourceManager.GetString("BtnApplyTemplateTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die delete selected template ähnelt.
        /// </summary>
        public static string BtnDeleteTemplateTooltip {
            get {
                return ResourceManager.GetString("BtnDeleteTemplateTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die edit selected template ähnelt.
        /// </summary>
        public static string BtnEditTemplateTooltip {
            get {
                return ResourceManager.GetString("BtnEditTemplateTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Finish ähnelt.
        /// </summary>
        public static string BtnFinishCaption {
            get {
                return ResourceManager.GetString("BtnFinishCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import ähnelt.
        /// </summary>
        public static string BtnImportTemplateCaption {
            get {
                return ResourceManager.GetString("BtnImportTemplateCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Templates ähnelt.
        /// </summary>
        public static string BtnTemplates {
            get {
                return ResourceManager.GetString("BtnTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die show templates ähnelt.
        /// </summary>
        public static string BtnTemplatesTooltip {
            get {
                return ResourceManager.GetString("BtnTemplatesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die cash flow statement ähnelt.
        /// </summary>
        public static string CashFlowStatement {
            get {
                return ResourceManager.GetString("CashFlowStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change ähnelt.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change Password ähnelt.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rights ähnelt.
        /// </summary>
        public static string ChangeRoleRights {
            get {
                return ResourceManager.GetString("ChangeRoleRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change Template (Step 1: Delete the current assignments) ähnelt.
        /// </summary>
        public static string ChangeTemplate1 {
            get {
                return ResourceManager.GetString("ChangeTemplate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change Template (Step 2: Create the new assignments) ähnelt.
        /// </summary>
        public static string ChangeTemplate2 {
            get {
                return ResourceManager.GetString("ChangeTemplate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change template (Step 3: Save the new assignments) ähnelt.
        /// </summary>
        public static string ChangeTemplate3 {
            get {
                return ResourceManager.GetString("ChangeTemplate3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change template (Step 4: Transfer of ähnelt.
        /// </summary>
        public static string ChangeTemplate4 {
            get {
                return ResourceManager.GetString("ChangeTemplate4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rights ähnelt.
        /// </summary>
        public static string ChangeUserRights {
            get {
                return ResourceManager.GetString("ChangeUserRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die overwrite option &quot;sum up positions without defined computation rules&quot;? ähnelt.
        /// </summary>
        public static string ChkReplaceAutoComputeEnabledFlagCaption {
            get {
                return ResourceManager.GetString("ChkReplaceAutoComputeEnabledFlagCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die overwrite option &quot;ignor warning message&quot;? ähnelt.
        /// </summary>
        public static string ChkReplaceIgnoreWarningMessageFlagCaption {
            get {
                return ResourceManager.GetString("ChkReplaceIgnoreWarningMessageFlagCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die overwrite option &quot;send account balances&quot;? ähnelt.
        /// </summary>
        public static string ChkReplaceSendAccountBalanceFlagCaption {
            get {
                return ResourceManager.GetString("ChkReplaceSendAccountBalanceFlagCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear filter ähnelt.
        /// </summary>
        public static string ClearFilterToolTip {
            get {
                return ResourceManager.GetString("ClearFilterToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The account could not be added to the template, since the target position is calculated. ähnelt.
        /// </summary>
        public static string ColudNotAddTaxonomyCalculated {
            get {
                return ResourceManager.GetString("ColudNotAddTaxonomyCalculated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The account could not be added to the template, since the target position in the template is not active. ähnelt.
        /// </summary>
        public static string ColudNotAddTaxonomyNotActive {
            get {
                return ResourceManager.GetString("ColudNotAddTaxonomyNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The account could not be assigned because the target position in the taxonomy is calculated. ähnelt.
        /// </summary>
        public static string ColudNotAssignTaxonomyCalculated {
            get {
                return ResourceManager.GetString("ColudNotAssignTaxonomyCalculated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The account could not be assigned because the target position in the taxonomy is not active. ähnelt.
        /// </summary>
        public static string ColudNotAssignTaxonomyNotActive {
            get {
                return ResourceManager.GetString("ColudNotAssignTaxonomyNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Comment ähnelt.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Companies ähnelt.
        /// </summary>
        public static string Companies {
            get {
                return ResourceManager.GetString("Companies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Company administrator ähnelt.
        /// </summary>
        public static string CompanyAdministrator {
            get {
                return ResourceManager.GetString("CompanyAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die At least one company should be selected. ähnelt.
        /// </summary>
        public static string CompanyAdminNoCompanySelectedError {
            get {
                return ResourceManager.GetString("CompanyAdminNoCompanySelectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Master Data Import ähnelt.
        /// </summary>
        public static string CompanyDataImport {
            get {
                return ResourceManager.GetString("CompanyDataImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select the Example CSV File with the company data, each CSV file which contains master data from a company. You can export an example of a company in CSV format to produce the required format. ähnelt.
        /// </summary>
        public static string CompanyDataImportInfo {
            get {
                return ResourceManager.GetString("CompanyDataImportInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die config ähnelt.
        /// </summary>
        public static string Config {
            get {
                return ResourceManager.GetString("Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Conflicts ähnelt.
        /// </summary>
        public static string ConflictsCaption {
            get {
                return ResourceManager.GetString("ConflictsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is a hidden position with value. ähnelt.
        /// </summary>
        public static string ContainsHiddenValueMessage {
            get {
                return ResourceManager.GetString("ContainsHiddenValueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy ähnelt.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not find node in presentation tree. ähnelt.
        /// </summary>
        public static string CouldNotFindNodePresentationTree {
            get {
                return ResourceManager.GetString("CouldNotFindNodePresentationTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die convert to account of exchange ähnelt.
        /// </summary>
        public static string CreateAcceptanceAccount {
            get {
                return ResourceManager.GetString("CreateAcceptanceAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create new template ähnelt.
        /// </summary>
        public static string CreateNewTemplate {
            get {
                return ResourceManager.GetString("CreateNewTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CSV files ready to import ähnelt.
        /// </summary>
        public static string CsvFileListToImport {
            get {
                return ResourceManager.GetString("CsvFileListToImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current taxonomy position: ähnelt.
        /// </summary>
        public static string CurrentTaxonomyPosition {
            get {
                return ResourceManager.GetString("CurrentTaxonomyPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die default report ähnelt.
        /// </summary>
        public static string DefaultReportName {
            get {
                return ResourceManager.GetString("DefaultReportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete all ähnelt.
        /// </summary>
        public static string DeleteAll {
            get {
                return ResourceManager.GetString("DeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The selected user could not be deleted since it is actually logged on. ähnelt.
        /// </summary>
        public static string DeleteCurrentUserNotAllowed {
            get {
                return ResourceManager.GetString("DeleteCurrentUserNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User could not be deleted ähnelt.
        /// </summary>
        public static string DeleteCurrentUserNotAllowedCaption {
            get {
                return ResourceManager.GetString("DeleteCurrentUserNotAllowedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure that the role {0} should be deleted? ähnelt.
        /// </summary>
        public static string DeleteRoleRequest {
            get {
                return ResourceManager.GetString("DeleteRoleRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete role? ähnelt.
        /// </summary>
        public static string DeleteRoleRequestTitle {
            get {
                return ResourceManager.GetString("DeleteRoleRequestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete role (DEL) ähnelt.
        /// </summary>
        public static string DeleteRoleTooltip {
            get {
                return ResourceManager.GetString("DeleteRoleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete Selected Rows ähnelt.
        /// </summary>
        public static string DeleteRowsButton {
            get {
                return ResourceManager.GetString("DeleteRowsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete selected items ähnelt.
        /// </summary>
        public static string DeleteSelectedItems {
            get {
                return ResourceManager.GetString("DeleteSelectedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to delete the template {0} ? ähnelt.
        /// </summary>
        public static string DeleteTemplateRequest {
            get {
                return ResourceManager.GetString("DeleteTemplateRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete template? ähnelt.
        /// </summary>
        public static string DeleteTemplateRequestTitle {
            get {
                return ResourceManager.GetString("DeleteTemplateRequestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure that the user {0} should be deleted? ähnelt.
        /// </summary>
        public static string DeleteUserRequest {
            get {
                return ResourceManager.GetString("DeleteUserRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete user? ähnelt.
        /// </summary>
        public static string DeleteUserRequestTitle {
            get {
                return ResourceManager.GetString("DeleteUserRequestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete user (DEL) ähnelt.
        /// </summary>
        public static string DeleteUserTooltip {
            get {
                return ResourceManager.GetString("DeleteUserTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die denied due to deny in role &quot;{0}&quot; ähnelt.
        /// </summary>
        public static string Denied {
            get {
                return ResourceManager.GetString("Denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die denied due to explicit deny rights of the user &quot;{0}&quot; ähnelt.
        /// </summary>
        public static string DeniedUser {
            get {
                return ResourceManager.GetString("DeniedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description ähnelt.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Difference values ​​between trade balance and fiscal balance ähnelt.
        /// </summary>
        public static string DifferenceBetweenTradeBalanceAndFiscalBalance {
            get {
                return ResourceManager.GetString("DifferenceBetweenTradeBalanceAndFiscalBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export template ähnelt.
        /// </summary>
        public static string DlgExportTemplateCaption {
            get {
                return ResourceManager.GetString("DlgExportTemplateCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export deleted elements as PDF File ähnelt.
        /// </summary>
        public static string DlgExportTemplateDeletedElementsCaption {
            get {
                return ResourceManager.GetString("DlgExportTemplateDeletedElementsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import template ähnelt.
        /// </summary>
        public static string DlgImportTemplateCaption {
            get {
                return ResourceManager.GetString("DlgImportTemplateCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Report Changes ähnelt.
        /// </summary>
        public static string DlgShowReportChanges {
            get {
                return ResourceManager.GetString("DlgShowReportChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Results of taxonomy update ähnelt.
        /// </summary>
        public static string DlgShowTemplateTaxonomyUpdateResults {
            get {
                return ResourceManager.GetString("DlgShowTemplateTaxonomyUpdateResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Templates for account assignments (details) ähnelt.
        /// </summary>
        public static string DlgTemplateDetailsCaption {
            get {
                return ResourceManager.GetString("DlgTemplateDetailsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Account mapping templates ähnelt.
        /// </summary>
        public static string DlgTemplatesCaption {
            get {
                return ResourceManager.GetString("DlgTemplatesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die eBalance-Kit ähnelt.
        /// </summary>
        public static string eBalanceKit {
            get {
                return ResourceManager.GetString("eBalanceKit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die eBilanz-Kit error report ähnelt.
        /// </summary>
        public static string eBalanceKitErrorReport {
            get {
                return ResourceManager.GetString("eBalanceKitErrorReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit role ähnelt.
        /// </summary>
        public static string EditRoleCaption {
            get {
                return ResourceManager.GetString("EditRoleCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die edit role rights (F3) ähnelt.
        /// </summary>
        public static string EditRoleRightsTooltip {
            get {
                return ResourceManager.GetString("EditRoleRightsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit role (F2) ähnelt.
        /// </summary>
        public static string EditRoleTooltip {
            get {
                return ResourceManager.GetString("EditRoleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit user ähnelt.
        /// </summary>
        public static string EditUserCaption {
            get {
                return ResourceManager.GetString("EditUserCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit user rights (F3) ähnelt.
        /// </summary>
        public static string EditUserRightsTooltip {
            get {
                return ResourceManager.GetString("EditUserRightsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit user (F2) ähnelt.
        /// </summary>
        public static string EditUserTooltip {
            get {
                return ResourceManager.GetString("EditUserTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die effective rights for user ähnelt.
        /// </summary>
        public static string EffectiveRightsCaption {
            get {
                return ResourceManager.GetString("EffectiveRightsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die no name ähnelt.
        /// </summary>
        public static string EmptyName {
            get {
                return ResourceManager.GetString("EmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Encoding ähnelt.
        /// </summary>
        public static string Encoding {
            get {
                return ResourceManager.GetString("Encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filter ähnelt.
        /// </summary>
        public static string EnterFilterText {
            get {
                return ResourceManager.GetString("EnterFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Errors ähnelt.
        /// </summary>
        public static string ErrorsCaption {
            get {
                return ResourceManager.GetString("ErrorsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Example CSV file ähnelt.
        /// </summary>
        public static string ExampleCsvFile {
            get {
                return ResourceManager.GetString("ExampleCsvFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Extend template ähnelt.
        /// </summary>
        public static string ExtendTemplate {
            get {
                return ResourceManager.GetString("ExtendTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file does already exist and will be replaced. ähnelt.
        /// </summary>
        public static string FileExistsWarning {
            get {
                return ResourceManager.GetString("FileExistsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die csv files (*.csv)|*.csv ähnelt.
        /// </summary>
        public static string FileFilterCsv {
            get {
                return ResourceManager.GetString("FileFilterCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die pdf files (*.pdf)|*.pdf ähnelt.
        /// </summary>
        public static string FileFilterPdf {
            get {
                return ResourceManager.GetString("FileFilterPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die xml files (*.xml)|*.xml ähnelt.
        /// </summary>
        public static string FileFilterXbrl {
            get {
                return ResourceManager.GetString("FileFilterXbrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filename ähnelt.
        /// </summary>
        public static string Filename {
            get {
                return ResourceManager.GetString("Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die files ähnelt.
        /// </summary>
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File save successful ähnelt.
        /// </summary>
        public static string FileSaved {
            get {
                return ResourceManager.GetString("FileSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File saved successfully do you want it to open now? ähnelt.
        /// </summary>
        public static string FileSaveSuccessfulOpen {
            get {
                return ResourceManager.GetString("FileSaveSuccessfulOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filter ähnelt.
        /// </summary>
        public static string FilterCaption {
            get {
                return ResourceManager.GetString("FilterCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filter options ähnelt.
        /// </summary>
        public static string FilterOptionsToolTip {
            get {
                return ResourceManager.GetString("FilterOptionsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The following positions were not found: {0} ähnelt.
        /// </summary>
        public static string FollowingPositionsNotFound {
            get {
                return ResourceManager.GetString("FollowingPositionsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General ähnelt.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Grant rights ähnelt.
        /// </summary>
        public static string Grant {
            get {
                return ResourceManager.GetString("Grant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die granted due to grant in role &quot;{0}&quot; ähnelt.
        /// </summary>
        public static string Granted {
            get {
                return ResourceManager.GetString("Granted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die granted due to explicit grant rights of the user &quot;{0}&quot; ähnelt.
        /// </summary>
        public static string GrantedUser {
            get {
                return ResourceManager.GetString("GrantedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The user &quot;{0}&quot; is the owner of the company and has full rights ähnelt.
        /// </summary>
        public static string GrantOwnerCompany {
            get {
                return ResourceManager.GetString("GrantOwnerCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The user &quot;{0}&quot; is the owner of the report and has full rights. The owner can be changed in the Management/Reports ähnelt.
        /// </summary>
        public static string GrantOwnerDocument {
            get {
                return ResourceManager.GetString("GrantOwnerDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This position contains a manual correction value. ähnelt.
        /// </summary>
        public static string HasManualValue {
            get {
                return ResourceManager.GetString("HasManualValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hide all positions ähnelt.
        /// </summary>
        public static string HideAllNodes {
            get {
                return ResourceManager.GetString("HideAllNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hide empty positions ähnelt.
        /// </summary>
        public static string HideEmptyPositions {
            get {
                return ResourceManager.GetString("HideEmptyPositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show only manual input ähnelt.
        /// </summary>
        public static string HideNonManualFields {
            get {
                return ResourceManager.GetString("HideNonManualFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please insert the &apos;Vereinheitlichtes Bundesschema&apos; ähnelt.
        /// </summary>
        public static string HintUsageVereinheitlichtesBundesschema {
            get {
                return ResourceManager.GetString("HintUsageVereinheitlichtesBundesschema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ignore all incorrect entries ähnelt.
        /// </summary>
        public static string IgnoreAllIncorrectEntries {
            get {
                return ResourceManager.GetString("IgnoreAllIncorrectEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ignore warning ähnelt.
        /// </summary>
        public static string IgnoreWarning {
            get {
                return ResourceManager.GetString("IgnoreWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import ähnelt.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import active directory user ähnelt.
        /// </summary>
        public static string ImportActiveDirectoryUserCaption {
            get {
                return ResourceManager.GetString("ImportActiveDirectoryUserCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add file ähnelt.
        /// </summary>
        public static string ImportAddFile {
            get {
                return ResourceManager.GetString("ImportAddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete selected file ähnelt.
        /// </summary>
        public static string ImportDeleteFile {
            get {
                return ResourceManager.GetString("ImportDeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} value(s) and {3} previous year values in {1} transaction(s) will be imported from {2} file(s) ähnelt.
        /// </summary>
        public static string ImportDetailedMessage {
            get {
                return ResourceManager.GetString("ImportDetailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select the CSV Data file ... ähnelt.
        /// </summary>
        public static string ImportDialogDescription {
            get {
                return ResourceManager.GetString("ImportDialogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data import ähnelt.
        /// </summary>
        public static string ImportDialogTitle {
            get {
                return ResourceManager.GetString("ImportDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data to be imported were validated and no errors found ähnelt.
        /// </summary>
        public static string ImportNoErrorsFound {
            get {
                return ResourceManager.GetString("ImportNoErrorsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The following rows were invalid ähnelt.
        /// </summary>
        public static string ImportRowErrorCaption {
            get {
                return ResourceManager.GetString("ImportRowErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sample CSV-Data export ähnelt.
        /// </summary>
        public static string ImportSampleDataExport {
            get {
                return ResourceManager.GetString("ImportSampleDataExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To import CSV files ähnelt.
        /// </summary>
        public static string ImportToImportCsvFiles {
            get {
                return ResourceManager.GetString("ImportToImportCsvFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die income statement ähnelt.
        /// </summary>
        public static string IncomeStatement {
            get {
                return ResourceManager.GetString("IncomeStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        public static string IncorrectTaxonomyIdListTitle {
            get {
                return ResourceManager.GetString("IncorrectTaxonomyIdListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die rights are inherited from &quot;{0}&quot; ähnelt.
        /// </summary>
        public static string InheritedFrom {
            get {
                return ResourceManager.GetString("InheritedFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Initialization ähnelt.
        /// </summary>
        public static string Initialization {
            get {
                return ResourceManager.GetString("Initialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Initializing database ähnelt.
        /// </summary>
        public static string InitializingDatabase {
            get {
                return ResourceManager.GetString("InitializingDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Input mode ähnelt.
        /// </summary>
        public static string InputMode {
            get {
                return ResourceManager.GetString("InputMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die installation ähnelt.
        /// </summary>
        public static string Installation {
            get {
                return ResourceManager.GetString("Installation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die install service ähnelt.
        /// </summary>
        public static string InstallService {
            get {
                return ResourceManager.GetString("InstallService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die insufficient rights ähnelt.
        /// </summary>
        public static string InsufficientRights {
            get {
                return ResourceManager.GetString("InsufficientRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open the dialog on next startup? ähnelt.
        /// </summary>
        public static string IsKeepNextOpen {
            get {
                return ResourceManager.GetString("IsKeepNextOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language ähnelt.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Line number ähnelt.
        /// </summary>
        public static string LineNumber {
            get {
                return ResourceManager.GetString("LineNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die loading active directory users... ähnelt.
        /// </summary>
        public static string LoadingActiveDirectoryUsers {
            get {
                return ResourceManager.GetString("LoadingActiveDirectoryUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loading positions... ähnelt.
        /// </summary>
        public static string LoadingPositions {
            get {
                return ResourceManager.GetString("LoadingPositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Management ähnelt.
        /// </summary>
        public static string Management {
            get {
                return ResourceManager.GetString("Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die mandatory field, proof of accounts wished ähnelt.
        /// </summary>
        public static string MandatoryFieldProofOfAccountsWished {
            get {
                return ResourceManager.GetString("MandatoryFieldProofOfAccountsWished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No password entered. ähnelt.
        /// </summary>
        public static string MissingPasswordError {
            get {
                return ResourceManager.GetString("MissingPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Database upgrade happened. Can&apos;t find the readme file about the database upgrade. ähnelt.
        /// </summary>
        public static string MissingUpgradeReadme {
            get {
                return ResourceManager.GetString("MissingUpgradeReadme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You have no permission to change this right. ähnelt.
        /// </summary>
        public static string ModifyRightNotAllowed {
            get {
                return ResourceManager.GetString("ModifyRightNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die It is not possible to change the right on the selected level. ähnelt.
        /// </summary>
        public static string ModifyRightNotPossible {
            get {
                return ResourceManager.GetString("ModifyRightNotPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New ähnelt.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die assistant for new reconciliation ähnelt.
        /// </summary>
        public static string NewReconciliationAssistant {
            get {
                return ResourceManager.GetString("NewReconciliationAssistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New value ähnelt.
        /// </summary>
        public static string NewValueLabel {
            get {
                return ResourceManager.GetString("NewValueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die NavigateNext ähnelt.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No ähnelt.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No conflicts found ähnelt.
        /// </summary>
        public static string NoConflictsFound {
            get {
                return ResourceManager.GetString("NoConflictsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No errors found ähnelt.
        /// </summary>
        public static string NoErrorsFound {
            get {
                return ResourceManager.GetString("NoErrorsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die unprofiled import ähnelt.
        /// </summary>
        public static string NoProfile {
            get {
                return ResourceManager.GetString("NoProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die not set ähnelt.
        /// </summary>
        public static string NotSet {
            get {
                return ResourceManager.GetString("NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die not specified ähnelt.
        /// </summary>
        public static string NotSpecified {
            get {
                return ResourceManager.GetString("NotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Old value ähnelt.
        /// </summary>
        public static string OldValueLabel {
            get {
                return ResourceManager.GetString("OldValueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open ähnelt.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file cannot be opened ähnelt.
        /// </summary>
        public static string OpenFileEror {
            get {
                return ResourceManager.GetString("OpenFileEror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Option ähnelt.
        /// </summary>
        public static string Option {
            get {
                return ResourceManager.GetString("Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Options ähnelt.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die overwrite the mapping ähnelt.
        /// </summary>
        public static string OverwriteMapping {
            get {
                return ResourceManager.GetString("OverwriteMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Page  ähnelt.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password ähnelt.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password (repeat) ähnelt.
        /// </summary>
        public static string Password1 {
            get {
                return ResourceManager.GetString("Password1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The entered passwords are not equal. ähnelt.
        /// </summary>
        public static string PaswordsNotEqualError {
            get {
                return ResourceManager.GetString("PaswordsNotEqualError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select... ähnelt.
        /// </summary>
        public static string PleaseSelect {
            get {
                return ResourceManager.GetString("PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Positions ähnelt.
        /// </summary>
        public static string Positions {
            get {
                return ResourceManager.GetString("Positions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Positions reference List ähnelt.
        /// </summary>
        public static string PositionsReferenceList {
            get {
                return ResourceManager.GetString("PositionsReferenceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Positions add up ähnelt.
        /// </summary>
        public static string PositionSumUp {
            get {
                return ResourceManager.GetString("PositionSumUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preview (the first 200 lines is shown) ähnelt.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Previous taxonomy position: ähnelt.
        /// </summary>
        public static string PreviousTaxonomyPosition {
            get {
                return ResourceManager.GetString("PreviousTaxonomyPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy report ... ähnelt.
        /// </summary>
        public static string ProgressCopyReport {
            get {
                return ResourceManager.GetString("ProgressCopyReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die creating report... ähnelt.
        /// </summary>
        public static string ProgressCreatingReport {
            get {
                return ResourceManager.GetString("ProgressCreatingReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Report is loading ... ähnelt.
        /// </summary>
        public static string ProgressReportLoading {
            get {
                return ResourceManager.GetString("ProgressReportLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die prohibited according to commercial law ähnelt.
        /// </summary>
        public static string ProhibitedAccordingToCommercialLaw {
            get {
                return ResourceManager.GetString("ProhibitedAccordingToCommercialLaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die prohibited according to tax law ähnelt.
        /// </summary>
        public static string ProhibitedAccordingToTaxLaw {
            get {
                return ResourceManager.GetString("ProhibitedAccordingToTaxLaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Read ähnelt.
        /// </summary>
        public static string Read {
            get {
                return ResourceManager.GetString("Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reference List ähnelt.
        /// </summary>
        public static string ReferenceList {
            get {
                return ResourceManager.GetString("ReferenceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Report ähnelt.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reports ähnelt.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die retain previous mapping ähnelt.
        /// </summary>
        public static string RetainPreviousMapping {
            get {
                return ResourceManager.GetString("RetainPreviousMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rights ähnelt.
        /// </summary>
        public static string Rights {
            get {
                return ResourceManager.GetString("Rights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rights for role ähnelt.
        /// </summary>
        public static string RightsForRole {
            get {
                return ResourceManager.GetString("RightsForRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rights for user ähnelt.
        /// </summary>
        public static string RightsForUser {
            get {
                return ResourceManager.GetString("RightsForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All ähnelt.
        /// </summary>
        public static string RightTreeNodeAllCaption {
            get {
                return ResourceManager.GetString("RightTreeNodeAllCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Other report components ähnelt.
        /// </summary>
        public static string RightTreeNodeOtherReportsCaption {
            get {
                return ResourceManager.GetString("RightTreeNodeOtherReportsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reconciliation ähnelt.
        /// </summary>
        public static string RightTreeNodeReconciliationCaption {
            get {
                return ResourceManager.GetString("RightTreeNodeReconciliationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Role ähnelt.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name is not allowed to be empty. ähnelt.
        /// </summary>
        public static string RoleNameErrorEmpty {
            get {
                return ResourceManager.GetString("RoleNameErrorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name is already used. ähnelt.
        /// </summary>
        public static string RoleNameErrorUsed {
            get {
                return ResourceManager.GetString("RoleNameErrorUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Roles ähnelt.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save as pdf file ähnelt.
        /// </summary>
        public static string SaveAsPdf {
            get {
                return ResourceManager.GetString("SaveAsPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while saving file ähnelt.
        /// </summary>
        public static string SaveFileEror {
            get {
                return ResourceManager.GetString("SaveFileEror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Security ähnelt.
        /// </summary>
        public static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die select destination ähnelt.
        /// </summary>
        public static string SelectDestination {
            get {
                return ResourceManager.GetString("SelectDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die selected template:  ähnelt.
        /// </summary>
        public static string SelectedTemplate {
            get {
                return ResourceManager.GetString("SelectedTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select filename ähnelt.
        /// </summary>
        public static string SelectFilename {
            get {
                return ResourceManager.GetString("SelectFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select folder ähnelt.
        /// </summary>
        public static string SelectFolder {
            get {
                return ResourceManager.GetString("SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die self ähnelt.
        /// </summary>
        public static string Self {
            get {
                return ResourceManager.GetString("Self", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Send ähnelt.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Send account balance ähnelt.
        /// </summary>
        public static string SendAccountBalance {
            get {
                return ResourceManager.GetString("SendAccountBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Separator ähnelt.
        /// </summary>
        public static string Separator {
            get {
                return ResourceManager.GetString("Separator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die show all positions ähnelt.
        /// </summary>
        public static string ShowAllNodes {
            get {
                return ResourceManager.GetString("ShowAllNodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Effective rights ähnelt.
        /// </summary>
        public static string ShowEffectiveRights {
            get {
                return ResourceManager.GetString("ShowEffectiveRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die show effective rights (F4) ähnelt.
        /// </summary>
        public static string ShowEffectiveRightsTooltip {
            get {
                return ResourceManager.GetString("ShowEffectiveRightsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show only mandatory positions ähnelt.
        /// </summary>
        public static string ShowOnlyMandatoryPostions {
            get {
                return ResourceManager.GetString("ShowOnlyMandatoryPostions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show only positions for selected legal status ähnelt.
        /// </summary>
        public static string ShowOnlyPositionsForSelectedLegalStatus {
            get {
                return ResourceManager.GetString("ShowOnlyPositionsForSelectedLegalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Changing of the special accounting standard can change the used taxonomy. All values that are not available in the new taxonomy will be deleted.
        ///
        ///Beside this all account assignments and all table elements (Statement of changes in fixed assets, Statement of changes in equity) of the current report will be deleted.
        ///
        ///Do you wish to change the special acounting standard? ähnelt.
        /// </summary>
        public static string SpecialAccountingStandardChanged {
            get {
                return ResourceManager.GetString("SpecialAccountingStandardChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Changing special accounting standard ähnelt.
        /// </summary>
        public static string SpecialAccountingStandardChangedHeadline {
            get {
                return ResourceManager.GetString("SpecialAccountingStandardChangedHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unique name to identify the system ähnelt.
        /// </summary>
        public static string SystemNameTooltip {
            get {
                return ResourceManager.GetString("SystemNameTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Systems ähnelt.
        /// </summary>
        public static string Systems {
            get {
                return ResourceManager.GetString("Systems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tax balance sheet values ähnelt.
        /// </summary>
        public static string TaxBalanceSheetValues {
            get {
                return ResourceManager.GetString("TaxBalanceSheetValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Taxonomy Id ähnelt.
        /// </summary>
        public static string TaxonomyId {
            get {
                return ResourceManager.GetString("TaxonomyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The following taxonomy Ids were not found ähnelt.
        /// </summary>
        public static string TaxonomyIdNotFoundCaption {
            get {
                return ResourceManager.GetString("TaxonomyIdNotFoundCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The following values are invalid ähnelt.
        /// </summary>
        public static string TaxonomyIdValueInvalidCaption {
            get {
                return ResourceManager.GetString("TaxonomyIdValueInvalidCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Taxonomy position: ähnelt.
        /// </summary>
        public static string TaxonomyPosition {
            get {
                return ResourceManager.GetString("TaxonomyPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The template has been exported successfully. ähnelt.
        /// </summary>
        public static string TemplateExportSucceed {
            get {
                return ResourceManager.GetString("TemplateExportSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The selected template has no assigned taxonomy. ähnelt.
        /// </summary>
        public static string TemplateHasNoAssignedTaxonomy {
            get {
                return ResourceManager.GetString("TemplateHasNoAssignedTaxonomy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a name for the template. ähnelt.
        /// </summary>
        public static string TemplateHasNoName {
            get {
                return ResourceManager.GetString("TemplateHasNoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The template is applied. ähnelt.
        /// </summary>
        public static string TemplateIsApplied {
            get {
                return ResourceManager.GetString("TemplateIsApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Text Delimiter ähnelt.
        /// </summary>
        public static string TextDelimiter {
            get {
                return ResourceManager.GetString("TextDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update template to newest taxonomy version ähnelt.
        /// </summary>
        public static string UpdateTemplate {
            get {
                return ResourceManager.GetString("UpdateTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Updating taxonomy version ähnelt.
        /// </summary>
        public static string UpdatingTaxonomyVersion {
            get {
                return ResourceManager.GetString("UpdatingTaxonomyVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User ähnelt.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Active Directory Import ähnelt.
        /// </summary>
        public static string UserImportActiveDirectory {
            get {
                return ResourceManager.GetString("UserImportActiveDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User management ähnelt.
        /// </summary>
        public static string UserManagement {
            get {
                return ResourceManager.GetString("UserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Full name ähnelt.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Users ähnelt.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shortname ähnelt.
        /// </summary>
        public static string UserShortname {
            get {
                return ResourceManager.GetString("UserShortname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shortname is not allowed to be empty. ähnelt.
        /// </summary>
        public static string UserShortnameErrorEmpty {
            get {
                return ResourceManager.GetString("UserShortnameErrorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shortname is already used. ähnelt.
        /// </summary>
        public static string UserShortnameErrorUsed {
            get {
                return ResourceManager.GetString("UserShortnameErrorUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die validating... ähnelt.
        /// </summary>
        public static string validationProgressMsg {
            get {
                return ResourceManager.GetString("validationProgressMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value ähnelt.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die value is computed ähnelt.
        /// </summary>
        public static string ValueIsComputed {
            get {
                return ResourceManager.GetString("ValueIsComputed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die value is locked due to conlicting computations with other value inputs ähnelt.
        /// </summary>
        public static string ValueIsLocked {
            get {
                return ResourceManager.GetString("ValueIsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die value has to be numeric ähnelt.
        /// </summary>
        public static string ValueMustBeNumeric {
            get {
                return ResourceManager.GetString("ValueMustBeNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die value will be summarized negative ähnelt.
        /// </summary>
        public static string ValueSumNegative {
            get {
                return ResourceManager.GetString("ValueSumNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die value will be summarized positive ähnelt.
        /// </summary>
        public static string ValueSumPositive {
            get {
                return ResourceManager.GetString("ValueSumPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Would you like to apply the template to the currently loaded report?
        ///
        ///Note: When you apply the template all existing mapings of the selected balance tree will be replaced with the mappings in the template. ähnelt.
        /// </summary>
        public static string WouldYouLikeApplyTemplateCurrentReport {
            get {
                return ResourceManager.GetString("WouldYouLikeApplyTemplateCurrentReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Would you like to update the template to the current Taxonomy version? ähnelt.
        /// </summary>
        public static string WouldYouLikeUpdateTemplateTaxonomy {
            get {
                return ResourceManager.GetString("WouldYouLikeUpdateTemplateTaxonomy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Write ähnelt.
        /// </summary>
        public static string Write {
            get {
                return ResourceManager.GetString("Write", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes ähnelt.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
