//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemDb.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abrechnung.
        /// </summary>
        internal static string Abrechnung {
            get {
                return ResourceManager.GetString("Abrechnung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affiliate.
        /// </summary>
        internal static string affiliate {
            get {
                return ResourceManager.GetString("affiliate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affiliate.
        /// </summary>
        internal static string affiliate1 {
            get {
                return ResourceManager.GetString("affiliate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Management.
        /// </summary>
        internal static string am {
            get {
                return ResourceManager.GetString("am", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string andere {
            get {
                return ResourceManager.GetString("andere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anlagenbuchhaltung.
        /// </summary>
        internal static string Anlagenbuchhaltung {
            get {
                return ResourceManager.GetString("Anlagenbuchhaltung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Payables / Vendors.
        /// </summary>
        internal static string ap {
            get {
                return ResourceManager.GetString("ap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Receivable / Customers.
        /// </summary>
        internal static string ar {
            get {
                return ResourceManager.GetString("ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belege.
        /// </summary>
        internal static string belege {
            get {
                return ResourceManager.GetString("belege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belege.
        /// </summary>
        internal static string belege1 {
            get {
                return ResourceManager.GetString("belege1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board.
        /// </summary>
        internal static string board {
            get {
                return ResourceManager.GetString("board", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget.
        /// </summary>
        internal static string bu {
            get {
                return ResourceManager.GetString("bu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget Projekte.
        /// </summary>
        internal static string BudgetProjekte {
            get {
                return ResourceManager.GetString("BudgetProjekte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controlling.
        /// </summary>
        internal static string co {
            get {
                return ResourceManager.GetString("co", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CS.
        /// </summary>
        internal static string CS {
            get {
                return ResourceManager.GetString("CS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debitoren.
        /// </summary>
        internal static string Debitoren {
            get {
                return ResourceManager.GetString("Debitoren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einkauf / Disposition.
        /// </summary>
        internal static string disposition {
            get {
                return ResourceManager.GetString("disposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einkauf.
        /// </summary>
        internal static string Einkauf {
            get {
                return ResourceManager.GetString("Einkauf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase.
        /// </summary>
        internal static string ek {
            get {
                return ResourceManager.GetString("ek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energiedatenmanagement.
        /// </summary>
        internal static string Energiedatenmanagement {
            get {
                return ResourceManager.GetString("Energiedatenmanagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Ledger.
        /// </summary>
        internal static string fi {
            get {
                return ResourceManager.GetString("fi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finance.
        /// </summary>
        internal static string finance {
            get {
                return ResourceManager.GetString("finance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geräteverwaltung.
        /// </summary>
        internal static string Geräteverwaltung {
            get {
                return ResourceManager.GetString("Geräteverwaltung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Händler.
        /// </summary>
        internal static string haendler {
            get {
                return ResourceManager.GetString("haendler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Händler.
        /// </summary>
        internal static string haendler1 {
            get {
                return ResourceManager.GetString("haendler1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hauptbuch.
        /// </summary>
        internal static string Hauptbuch {
            get {
                return ResourceManager.GetString("Hauptbuch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kooperationspartner.
        /// </summary>
        internal static string kooperationspartner {
            get {
                return ResourceManager.GetString("kooperationspartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kooperationspartner.
        /// </summary>
        internal static string kooperationspartner1 {
            get {
                return ResourceManager.GetString("kooperationspartner1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kostenstellen.
        /// </summary>
        internal static string Kostenstellen {
            get {
                return ResourceManager.GetString("Kostenstellen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kreditoren.
        /// </summary>
        internal static string Kreditoren {
            get {
                return ResourceManager.GetString("Kreditoren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string languageName {
            get {
                return ResourceManager.GetString("languageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lieferantenwechsel.
        /// </summary>
        internal static string Lieferantenwechsel {
            get {
                return ResourceManager.GetString("Lieferantenwechsel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marktkommunikation.
        /// </summary>
        internal static string Marktkommunikation {
            get {
                return ResourceManager.GetString("Marktkommunikation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materialwirtschaft.
        /// </summary>
        internal static string Materialwirtschaft {
            get {
                return ResourceManager.GetString("Materialwirtschaft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mitglieder.
        /// </summary>
        internal static string mitglieder {
            get {
                return ResourceManager.GetString("mitglieder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mitglieder.
        /// </summary>
        internal static string mitglieder1 {
            get {
                return ResourceManager.GetString("mitglieder1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Management.
        /// </summary>
        internal static string mm {
            get {
                return ResourceManager.GetString("mm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enjoy viewbox.
        /// </summary>
        internal static string motto {
            get {
                return ResourceManager.GetString("motto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DART.
        /// </summary>
        internal static string other {
            get {
                return ResourceManager.GetString("other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plant Management.
        /// </summary>
        internal static string pm {
            get {
                return ResourceManager.GetString("pm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PM.
        /// </summary>
        internal static string PM2 {
            get {
                return ResourceManager.GetString("PM2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profitcenter.
        /// </summary>
        internal static string Profitcenter {
            get {
                return ResourceManager.GetString("Profitcenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        internal static string report {
            get {
                return ResourceManager.GetString("report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Department.
        /// </summary>
        internal static string sd {
            get {
                return ResourceManager.GetString("sd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SD.
        /// </summary>
        internal static string SD2 {
            get {
                return ResourceManager.GetString("SD2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Data.
        /// </summary>
        internal static string stammdaten {
            get {
                return ResourceManager.GetString("stammdaten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stammdaten.
        /// </summary>
        internal static string Stammdaten1 {
            get {
                return ResourceManager.GetString("Stammdaten1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Übergreifend.
        /// </summary>
        internal static string Übergreifend {
            get {
                return ResourceManager.GetString("Übergreifend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple sections.
        /// </summary>
        internal static string ue {
            get {
                return ResourceManager.GetString("ue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verkauf.
        /// </summary>
        internal static string verkauf {
            get {
                return ResourceManager.GetString("verkauf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract header.
        /// </summary>
        internal static string vertragskonto {
            get {
                return ResourceManager.GetString("vertragskonto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertragskontokorrent.
        /// </summary>
        internal static string Vertragskontokorrent {
            get {
                return ResourceManager.GetString("Vertragskontokorrent", resourceCulture);
            }
        }
    }
}
