namespace ViewboxDb
{
	public enum ActionControllers
	{
		AccountLogOn,
		DataGridExecuteIssue,
		DataGridGroup,
		DataGridIndex,
		DataGridJoin,
		DataGridSortAndFilter,
		DataGridUpdateColumn,
		DocumentsIndex,
		ExportIndex,
		ExportStart,
		ExportDownload,
		ExportCancelJob,
		ExportMassExport,
		HelpIndex,
		HelpTableList,
		HelpIssueList,
		HelpViewList,
		HelpDocuments,
		HelpControlCenter,
		HelpExport,
		HelpSettings,
		HelpAbout,
		HelpFaq,
		IssueListIndex,
		SettingsIndex,
		SettingsPersonal,
		SettingsRights,
		TableListIndex,
		ViewListIndex
	}
}
