//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base.Localisation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcesCommon {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesCommon() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Base.Localisation.ResourcesCommon", typeof(ResourcesCommon).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge files.
        /// </summary>
        public static string AccessMerger_MergeFiles {
            get {
                return ResourceManager.GetString("AccessMerger_MergeFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output directory.
        /// </summary>
        public static string AccessMerger_OutputDirectory {
            get {
                return ResourceManager.GetString("AccessMerger_OutputDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output file label.
        /// </summary>
        public static string AccessMerger_OutputFileLabel {
            get {
                return ResourceManager.GetString("AccessMerger_OutputFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output file.
        /// </summary>
        public static string AccessMerger_OutputFileName {
            get {
                return ResourceManager.GetString("AccessMerger_OutputFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output tables contains input filename..
        /// </summary>
        public static string AccessMerger_OutputTablesWithLabels {
            get {
                return ResourceManager.GetString("AccessMerger_OutputTablesWithLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source directory.
        /// </summary>
        public static string AccessMerger_SourceDirectory {
            get {
                return ResourceManager.GetString("AccessMerger_SourceDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}-bit application.
        /// </summary>
        public static string ApplicationArchitecture {
            get {
                return ResourceManager.GetString("ApplicationArchitecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile management.
        /// </summary>
        public static string AssistantControl_Assistant {
            get {
                return ResourceManager.GetString("AssistantControl_Assistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bukrs.
        /// </summary>
        public static string AssistantControl_Bukrs {
            get {
                return ResourceManager.GetString("AssistantControl_Bukrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common data.
        /// </summary>
        public static string AssistantControl_CommonData {
            get {
                return ResourceManager.GetString("AssistantControl_CommonData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure data source.
        /// </summary>
        public static string AssistantControl_ConfigureDataSource {
            get {
                return ResourceManager.GetString("AssistantControl_ConfigureDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure default properties.
        /// </summary>
        public static string AssistantControl_ConfigureDefaultProperties {
            get {
                return ResourceManager.GetString("AssistantControl_ConfigureDefaultProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure output.
        /// </summary>
        public static string AssistantControl_ConfigureOutput {
            get {
                return ResourceManager.GetString("AssistantControl_ConfigureOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Viewbox database.
        /// </summary>
        public static string AssistantControl_ConfigureViewboxDb {
            get {
                return ResourceManager.GetString("AssistantControl_ConfigureViewboxDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        public static string AssistantControl_Database {
            get {
                return ResourceManager.GetString("AssistantControl_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database type.
        /// </summary>
        public static string AssistantControl_DatabaseType {
            get {
                return ResourceManager.GetString("AssistantControl_DatabaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select data source type.
        /// </summary>
        public static string AssistantControl_DatasourceType {
            get {
                return ResourceManager.GetString("AssistantControl_DatasourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gjahr.
        /// </summary>
        public static string AssistantControl_Gjahr {
            get {
                return ResourceManager.GetString("AssistantControl_Gjahr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandt.
        /// </summary>
        public static string AssistantControl_Mandt {
            get {
                return ResourceManager.GetString("AssistantControl_Mandt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string AssistantControl_Password {
            get {
                return ResourceManager.GetString("AssistantControl_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string AssistantControl_Port {
            get {
                return ResourceManager.GetString("AssistantControl_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process threads.
        /// </summary>
        public static string AssistantControl_ProcessThreads {
            get {
                return ResourceManager.GetString("AssistantControl_ProcessThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile name.
        /// </summary>
        public static string AssistantControl_ProfileName {
            get {
                return ResourceManager.GetString("AssistantControl_ProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string AssistantControl_Server {
            get {
                return ResourceManager.GetString("AssistantControl_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source type.
        /// </summary>
        public static string AssistantControl_SourceType {
            get {
                return ResourceManager.GetString("AssistantControl_SourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string AssistantControl_Username {
            get {
                return ResourceManager.GetString("AssistantControl_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merging is failed because size of files is bigger than 2 GB. .
        /// </summary>
        public static string BigFileSizeMergingException {
            get {
                return ResourceManager.GetString("BigFileSizeMergingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy files.
        /// </summary>
        public static string BtnAccessCopyFiles {
            get {
                return ResourceManager.GetString("BtnAccessCopyFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to files.
        /// </summary>
        public static string BtnAccessLinkingFile {
            get {
                return ResourceManager.GetString("BtnAccessLinkingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge files.
        /// </summary>
        public static string BtnAccessMergeFile {
            get {
                return ResourceManager.GetString("BtnAccessMergeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access operations.
        /// </summary>
        public static string BtnAccessOperations {
            get {
                return ResourceManager.GetString("BtnAccessOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze Db.
        /// </summary>
        public static string BtnDatabaseStructureAnalyze {
            get {
                return ResourceManager.GetString("BtnDatabaseStructureAnalyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit profile.
        /// </summary>
        public static string BtnEditProfileCaption {
            get {
                return ResourceManager.GetString("BtnEditProfileCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate view scripts.
        /// </summary>
        public static string BtnGenerateScripts {
            get {
                return ResourceManager.GetString("BtnGenerateScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About ViewAssistant.
        /// </summary>
        public static string BtnInfoAboutViewAssistant {
            get {
                return ResourceManager.GetString("BtnInfoAboutViewAssistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string BtnInfoCaption {
            get {
                return ResourceManager.GetString("BtnInfoCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current profile summary.
        /// </summary>
        public static string BtnInfoCurrentProfileSummary {
            get {
                return ResourceManager.GetString("BtnInfoCurrentProfileSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migrate metadata.
        /// </summary>
        public static string BtnMetaToViewbox {
            get {
                return ResourceManager.GetString("BtnMetaToViewbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migrate metadata with optimizations.
        /// </summary>
        public static string BtnMetaToViewboxOpt {
            get {
                return ResourceManager.GetString("BtnMetaToViewboxOpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        public static string BtnProfilesCaption {
            get {
                return ResourceManager.GetString("BtnProfilesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string BtnRefresh {
            get {
                return ResourceManager.GetString("BtnRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh all.
        /// </summary>
        public static string BtnRefreshAll {
            get {
                return ResourceManager.GetString("BtnRefreshAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test connection.
        /// </summary>
        public static string BtnTestConnectionCaption {
            get {
                return ResourceManager.GetString("BtnTestConnectionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer data.
        /// </summary>
        public static string BtnTransferData {
            get {
                return ResourceManager.GetString("BtnTransferData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string BtnUpload {
            get {
                return ResourceManager.GetString("BtnUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length:.
        /// </summary>
        public static string ColumnLength {
            get {
                return ResourceManager.GetString("ColumnLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter 1:.
        /// </summary>
        public static string ColumnList_Filter1 {
            get {
                return ResourceManager.GetString("ColumnList_Filter1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter 2:.
        /// </summary>
        public static string ColumnList_Filter2 {
            get {
                return ResourceManager.GetString("ColumnList_Filter2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column overview.
        /// </summary>
        public static string ColumnOverview {
            get {
                return ResourceManager.GetString("ColumnOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column selection.
        /// </summary>
        public static string Columnselection {
            get {
                return ResourceManager.GetString("Columnselection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;not set&gt;.
        /// </summary>
        public static string Common_ValueNotSet {
            get {
                return ResourceManager.GetString("Common_ValueNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string ConnectionState_Connected {
            get {
                return ResourceManager.GetString("ConnectionState_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not connected.
        /// </summary>
        public static string ConnectionState_NotConnected {
            get {
                return ResourceManager.GetString("ConnectionState_NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name contains special characters or whitespaces!.
        /// </summary>
        public static string ContainsSpecCharOrWhiteSpace {
            get {
                return ResourceManager.GetString("ContainsSpecCharOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coping files is finished but coping following files is failed:.
        /// </summary>
        public static string CopyFileError {
            get {
                return ResourceManager.GetString("CopyFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coping files is finished..
        /// </summary>
        public static string CopyFileFinishedSuccessfully {
            get {
                return ResourceManager.GetString("CopyFileFinishedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy files.
        /// </summary>
        public static string CopyFilesCommand {
            get {
                return ResourceManager.GetString("CopyFilesCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create localizations.
        /// </summary>
        public static string CreateLoc {
            get {
                return ResourceManager.GetString("CreateLoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create localizations where empty.
        /// </summary>
        public static string CreateLocIfEmpty {
            get {
                return ResourceManager.GetString("CreateLocIfEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating the following file(s) thrown errors:.
        /// </summary>
        public static string CreatingFileError {
            get {
                return ResourceManager.GetString("CreatingFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to database..
        /// </summary>
        public static string DatabaseConnectionFailed {
            get {
                return ResourceManager.GetString("DatabaseConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database connection has been successfully established..
        /// </summary>
        public static string DatabaseConnectionOk {
            get {
                return ResourceManager.GetString("DatabaseConnectionOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database type.
        /// </summary>
        public static string DatabaseType {
            get {
                return ResourceManager.GetString("DatabaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dataset overview.
        /// </summary>
        public static string DatasetOverview {
            get {
                return ResourceManager.GetString("DatasetOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datasetcount for preview.
        /// </summary>
        public static string DatasetPreviewCount {
            get {
                return ResourceManager.GetString("DatasetPreviewCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to datasets.
        /// </summary>
        public static string Datasets {
            get {
                return ResourceManager.GetString("Datasets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default properties.
        /// </summary>
        public static string DefaultProperties {
            get {
                return ResourceManager.GetString("DefaultProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access process.
        /// </summary>
        public static string DlgAccessProcess {
            get {
                return ResourceManager.GetString("DlgAccessProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data preview.
        /// </summary>
        public static string DlgDataPreviewTitle {
            get {
                return ResourceManager.GetString("DlgDataPreviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewAssistant.
        /// </summary>
        public static string DlgMainCaption {
            get {
                return ResourceManager.GetString("DlgMainCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile management.
        /// </summary>
        public static string DlgProfilesCaption {
            get {
                return ResourceManager.GetString("DlgProfilesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile summary.
        /// </summary>
        public static string DlgSummaryTitle {
            get {
                return ResourceManager.GetString("DlgSummaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty tables.
        /// </summary>
        public static string EmptyTables {
            get {
                return ResourceManager.GetString("EmptyTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax:.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables.
        /// </summary>
        public static string FilledTables {
            get {
                return ResourceManager.GetString("FilledTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filling every field is compulsory..
        /// </summary>
        public static string FillingEveryFieldCompulsory {
            get {
                return ResourceManager.GetString("FillingEveryFieldCompulsory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filter list.
        /// </summary>
        public static string FilterList {
            get {
                return ResourceManager.GetString("FilterList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final table&apos;s columns.
        /// </summary>
        public static string FinalColumns {
            get {
                return ResourceManager.GetString("FinalColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final tables.
        /// </summary>
        public static string FinalTables {
            get {
                return ResourceManager.GetString("FinalTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating view scripts is finished!.
        /// </summary>
        public static string GeneratingScriptFinished {
            get {
                return ResourceManager.GetString("GeneratingScriptFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide row counts.
        /// </summary>
        public static string HideRowCounts {
            get {
                return ResourceManager.GetString("HideRowCounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep.
        /// </summary>
        public static string Keep {
            get {
                return ResourceManager.GetString("Keep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to files.
        /// </summary>
        public static string LinkingFileCommand {
            get {
                return ResourceManager.GetString("LinkingFileCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linking files is failed!.
        /// </summary>
        public static string LinkingFilesFailed {
            get {
                return ResourceManager.GetString("LinkingFilesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linking files is finished successfully..
        /// </summary>
        public static string LinkingFilesSuccessful {
            get {
                return ResourceManager.GetString("LinkingFilesSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization settings.
        /// </summary>
        public static string LocalizationSettings {
            get {
                return ResourceManager.GetString("LocalizationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log directory.
        /// </summary>
        public static string LogDirectory {
            get {
                return ResourceManager.GetString("LogDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge files.
        /// </summary>
        public static string MergeFileCommand {
            get {
                return ResourceManager.GetString("MergeFileCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merging files is failed!.
        /// </summary>
        public static string MergingFilesFailed {
            get {
                return ResourceManager.GetString("MergingFilesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merging files is finished successfully..
        /// </summary>
        public static string MergingFilesSuccessful {
            get {
                return ResourceManager.GetString("MergingFilesSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New profile.
        /// </summary>
        public static string NewAssistant {
            get {
                return ResourceManager.GetString("NewAssistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next &gt;.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no name.
        /// </summary>
        public static string NoName {
            get {
                return ResourceManager.GetString("NoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not selected profile. .
        /// </summary>
        public static string NotSelectedProfile {
            get {
                return ResourceManager.GetString("NotSelectedProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are not selected viewbox tables..
        /// </summary>
        public static string NotSelectedViewBoxTables {
            get {
                return ResourceManager.GetString("NotSelectedViewBoxTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On column names.
        /// </summary>
        public static string OnColumnNames {
            get {
                return ResourceManager.GetString("OnColumnNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only for the empty ones.
        /// </summary>
        public static string OnlyForTheEmptyOnes {
            get {
                return ResourceManager.GetString("OnlyForTheEmptyOnes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On table names.
        /// </summary>
        public static string OnTableNames {
            get {
                return ResourceManager.GetString("OnTableNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output database properties.
        /// </summary>
        public static string OutputDbProperties {
            get {
                return ResourceManager.GetString("OutputDbProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel:.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        public static string Profiles {
            get {
                return ResourceManager.GetString("Profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename settings.
        /// </summary>
        public static string RenameSettings {
            get {
                return ResourceManager.GetString("RenameSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should the profile &apos;{0}&apos; really be deleted?.
        /// </summary>
        public static string RequestDeleteProfile {
            get {
                return ResourceManager.GetString("RequestDeleteProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string SearchBox_LabelText {
            get {
                return ResourceManager.GetString("SearchBox_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show only relevant tables.
        /// </summary>
        public static string ShowOnlyRelevantTables {
            get {
                return ResourceManager.GetString("ShowOnlyRelevantTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sort list.
        /// </summary>
        public static string SortList {
            get {
                return ResourceManager.GetString("SortList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source table&apos;s columns.
        /// </summary>
        public static string SourceColumns {
            get {
                return ResourceManager.GetString("SourceColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source database properties.
        /// </summary>
        public static string SourceDbProperties {
            get {
                return ResourceManager.GetString("SourceDbProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source tables.
        /// </summary>
        public static string SourceTables {
            get {
                return ResourceManager.GetString("SourceTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to step.
        /// </summary>
        public static string Step {
            get {
                return ResourceManager.GetString("Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support:.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog:.
        /// </summary>
        public static string TableInfoCatalog {
            get {
                return ResourceManager.GetString("TableInfoCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment:.
        /// </summary>
        public static string TableInfoComment {
            get {
                return ResourceManager.GetString("TableInfoComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datasets:.
        /// </summary>
        public static string TableInfoCount {
            get {
                return ResourceManager.GetString("TableInfoCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last transfer:.
        /// </summary>
        public static string TableInfoLastTransfer {
            get {
                return ResourceManager.GetString("TableInfoLastTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datasets destination:.
        /// </summary>
        public static string TableInfoLastTransferDestinationCount {
            get {
                return ResourceManager.GetString("TableInfoLastTransferDestinationCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration:.
        /// </summary>
        public static string TableInfoLastTransferDuration {
            get {
                return ResourceManager.GetString("TableInfoLastTransferDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error:.
        /// </summary>
        public static string TableInfoLastTransferError {
            get {
                return ResourceManager.GetString("TableInfoLastTransferError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter:.
        /// </summary>
        public static string TableInfoLastTransferFilter {
            get {
                return ResourceManager.GetString("TableInfoLastTransferFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datasets source:.
        /// </summary>
        public static string TableInfoLastTransferSourceCount {
            get {
                return ResourceManager.GetString("TableInfoLastTransferSourceCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema:.
        /// </summary>
        public static string TableInfoSchema {
            get {
                return ResourceManager.GetString("TableInfoSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table:.
        /// </summary>
        public static string TableInfoTable {
            get {
                return ResourceManager.GetString("TableInfoTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table selection.
        /// </summary>
        public static string Tableselection {
            get {
                return ResourceManager.GetString("Tableselection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Progress:.
        /// </summary>
        public static string TotalProgress {
            get {
                return ResourceManager.GetString("TotalProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update the Viewbox database.
        /// </summary>
        public static string UpgradeDatabase {
            get {
                return ResourceManager.GetString("UpgradeDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Viewbox database is out of date. The database should be updated, if not, then the current version of the View Builder cannot be used..
        /// </summary>
        public static string UpgradeMsg {
            get {
                return ResourceManager.GetString("UpgradeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uppercase first letters.
        /// </summary>
        public static string UppercaseFirstLetters {
            get {
                return ResourceManager.GetString("UppercaseFirstLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.{1}.{2}.{3}.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewbox table&apos;s columns.
        /// </summary>
        public static string ViewboxColumns {
            get {
                return ResourceManager.GetString("ViewboxColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewBox database properties.
        /// </summary>
        public static string ViewboxDbProperties {
            get {
                return ResourceManager.GetString("ViewboxDbProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewbox tables.
        /// </summary>
        public static string ViewboxTables {
            get {
                return ResourceManager.GetString("ViewboxTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace whitespaces of table name in output file.  .
        /// </summary>
        public static string WhiteSpaceSupportedInTables {
            get {
                return ResourceManager.GetString("WhiteSpaceSupportedInTables", resourceCulture);
            }
        }
    }
}
